import type{FinancialActivityConnections,FinancialActivityLine,FinancialActivityRecord,FinancialAmount,FinancialEvidenceReference,FinancialPayerKind,PaymentMethod}from'./contracts';
import{assertFinancialActivity}from'./invariants';

const now=()=>new Date().toISOString();
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const unique=(values:string[])=>[...new Set(values.map(value=>value.trim()).filter(Boolean))];
const connections=(value?:Partial<FinancialActivityConnections>):FinancialActivityConnections=>({personIds:unique(value?.personIds||[]),documentIds:unique(value?.documentIds||[]),decisionIds:unique(value?.decisionIds||[])});
export interface CreateFinancialActivityInput{kind?:FinancialActivityRecord['kind'];occurredOn:string;merchant:string;description:string;payer:{kind:FinancialPayerKind;name?:string};paymentMethod:PaymentMethod;lines:Omit<FinancialActivityLine,'id'>[];evidence?:FinancialEvidenceReference[];connections?:Partial<FinancialActivityConnections>;reimbursementRequired?:boolean;createdBy:string;correctionOfId?:string}
export function createFinancialActivity(input:CreateFinancialActivityInput):FinancialActivityRecord{
 const at=now();const lines=input.lines.map(line=>({...line,id:id('financial-line')}));const total:FinancialAmount={currency:'SEK',minorUnits:lines.reduce((sum,line)=>sum+line.amount.minorUnits,0)};
 const record:FinancialActivityRecord={id:id('financial-activity'),version:1,kind:input.kind||'purchase',status:'registered',occurredOn:input.occurredOn,merchant:input.merchant.trim(),description:input.description.trim(),payer:{kind:input.payer.kind,name:input.payer.name?.trim()||undefined},paymentMethod:input.paymentMethod,total,lines,evidence:input.evidence||[],reimbursement:{status:input.reimbursementRequired?'pending':'not_applicable',amount:input.reimbursementRequired?total:undefined},connections:connections(input.connections),correctionOfId:input.correctionOfId,history:[{id:id('financial-history'),at,by:input.createdBy,event:'created'}],createdAt:at,updatedAt:at};assertFinancialActivity(record);return record;
}
export function updateFinancialActivity(record:FinancialActivityRecord,patch:Partial<Pick<FinancialActivityRecord,'occurredOn'|'merchant'|'description'|'payer'|'paymentMethod'|'lines'|'evidence'|'connections'>>,actor:string,note?:string):FinancialActivityRecord{
 if(record.status==='reported'||record.status==='voided')throw new Error('Reported or voided activities cannot be edited; create a correction instead.');const at=now();const lines=patch.lines||record.lines;const next={...record,...patch,merchant:patch.merchant?.trim()??record.merchant,description:patch.description?.trim()??record.description,lines,total:{currency:'SEK' as const,minorUnits:lines.reduce((sum,line)=>sum+line.amount.minorUnits,0)},connections:patch.connections?connections(patch.connections):record.connections,history:[...record.history,{id:id('financial-history'),at,by:actor,event:'updated' as const,note}],updatedAt:at};assertFinancialActivity(next);return next;
}
export function reviewFinancialActivity(record:FinancialActivityRecord,actor:string,note?:string):FinancialActivityRecord{if(record.status!=='registered')throw new Error('Only registered activities can be reviewed.');const at=now();const next={...record,status:'reviewed' as const,history:[...record.history,{id:id('financial-history'),at,by:actor,event:'reviewed' as const,note}],updatedAt:at};assertFinancialActivity(next);return next}
export function markFinancialActivityReimbursed(record:FinancialActivityRecord,reimbursedOn:string,actor:string,note?:string):FinancialActivityRecord{if(record.reimbursement.status!=='pending')throw new Error('Only pending reimbursements can be marked reimbursed.');const at=now();const next={...record,reimbursement:{...record.reimbursement,status:'reimbursed' as const,reimbursedOn,note},history:[...record.history,{id:id('financial-history'),at,by:actor,event:'reimbursed' as const,note}],updatedAt:at};assertFinancialActivity(next);return next}
export function reportFinancialActivity(record:FinancialActivityRecord,reportingPeriodId:string,actor:string):FinancialActivityRecord{if(record.status!=='reviewed')throw new Error('Only reviewed activities can be reported.');const at=now();const next={...record,status:'reported' as const,reportingPeriodId,history:[...record.history,{id:id('financial-history'),at,by:actor,event:'reported' as const}],updatedAt:at};assertFinancialActivity(next);return next}
export function voidFinancialActivity(record:FinancialActivityRecord,actor:string,note:string):FinancialActivityRecord{if(record.status==='reported')throw new Error('Reported activities must be corrected, not voided.');const at=now();return{...record,status:'voided',history:[...record.history,{id:id('financial-history'),at,by:actor,event:'voided',note}],updatedAt:at}}
export function createCorrectionActivity(original:FinancialActivityRecord,input:Omit<CreateFinancialActivityInput,'kind'|'correctionOfId'>):FinancialActivityRecord{return createFinancialActivity({...input,kind:'correction',correctionOfId:original.id})}
