import{createLocalResourceRepository,type ResourceRecord,type ResourceTrust,type ResourceType}from'../resource';

export const RESOURCE_POPULATION_STORAGE_KEY='liv.resource-population-proposals.v1';
export const RESOURCE_POPULATION_CHANGE_EVENT='liv:resource-population-changed';
export type PopulationDecision='pending'|'approved'|'rejected';
export interface ResourcePopulationProposal{id:string;version:1;title:string;type:ResourceType;summary:string;whyThisMatters:string;topics:string[];keywords:string[];audience:string[];source:{author?:string;organisation?:string;publisher?:string;publicationDate?:string;language?:string};locator:{url?:string;isbn?:string};suggestedTrust:ResourceTrust;catalogue:string;decision:PopulationDecision;history:{id:string;at:string;by:string;event:'proposed'|'approved'|'rejected';note?:string}[];createdAt:string;updatedAt:string}
export interface PopulationSeed{key:string;title:string;type:ResourceType;summary:string;whyThisMatters:string;topics:string[];keywords?:string[];audience?:string[];organisation:string;url:string;trust:'official'|'professional';catalogue:string}
const normalise=(value:string)=>value.trim().toLocaleLowerCase('sv-SE').replace(/\s+/g,' ');
const read=(storage:Storage):ResourcePopulationProposal[]=>{try{const value=JSON.parse(storage.getItem(RESOURCE_POPULATION_STORAGE_KEY)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
const write=(storage:Storage,records:ResourcePopulationProposal[])=>{storage.setItem(RESOURCE_POPULATION_STORAGE_KEY,JSON.stringify(records));if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(RESOURCE_POPULATION_CHANGE_EVENT))};
const now=()=>new Date().toISOString();
export function createLocalResourcePopulationRepository(storage:Storage=localStorage){return{list:()=>read(storage),install(seeds:PopulationSeed[],by:string){const current=read(storage);const ids=new Set(current.map(item=>item.id));const at=now();const added=seeds.filter(seed=>!ids.has(`population:${seed.key}`)).map(seed=>({id:`population:${seed.key}`,version:1 as const,title:seed.title,type:seed.type,summary:seed.summary,whyThisMatters:seed.whyThisMatters,topics:seed.topics,keywords:seed.keywords||[],audience:seed.audience||['Familj','God man'],source:{organisation:seed.organisation,publisher:seed.organisation,language:'sv'},locator:{url:seed.url},suggestedTrust:seed.trust,catalogue:seed.catalogue,decision:'pending' as const,history:[{id:`population-history-${seed.key}-${Date.now()}`,at,by,event:'proposed' as const,note:'Installerad som granskningsförslag. Ingen resurs skapades automatiskt.'}],createdAt:at,updatedAt:at}));if(added.length)write(storage,[...added,...current]);return added.length},decide(id:string,decision:'approved'|'rejected',by:string,note?:string){const records=read(storage);const proposal=records.find(item=>item.id===id);if(!proposal)throw new Error('Förslaget finns inte längre.');if(proposal.decision===decision)return proposal;const at=now();if(decision==='approved'){const resources=createLocalResourceRepository(storage);const existing=resources.list().find(item=>(proposal.locator.url&&item.locator.url===proposal.locator.url)||normalise(item.title)===normalise(proposal.title));if(!existing){const resource:ResourceRecord={id:`resource:${proposal.id}`,version:1,title:proposal.title,type:proposal.type,summary:proposal.summary,whyThisMatters:proposal.whyThisMatters,topics:[...proposal.topics],keywords:[...proposal.keywords],audience:[...proposal.audience],source:{...proposal.source},locator:{...proposal.locator},availability:'available',connections:{personIds:[],documentIds:[],lifeEventIds:[],knowledgeTopicIds:[],decisionIds:[]},review:{trust:proposal.suggestedTrust,reviewedBy:by,reviewedAt:at,note:'Familjen granskade och godkände katalogförslaget.'},history:[{id:`resource-history-${proposal.id}-${Date.now()}`,at,by,event:'created',note:'Skapad genom Knowledge Population efter uttryckligt godkännande.'},{id:`resource-review-${proposal.id}-${Date.now()}`,at,by,event:'reviewed',note:'Källa och metadata godkända av familjen.'}],createdAt:at,updatedAt:at};resources.save(resource);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('liv:resources-changed',{detail:{resourceId:resource.id,action:'population-approved'}}))}}
 const updated={...proposal,decision,history:[...proposal.history,{id:`population-history-${Date.now()}`,at,by,event:decision,note}],updatedAt:at};write(storage,records.map(item=>item.id===id?updated:item));return updated}}}
