export type ReceiptImportDraftStatus='pending_review'|'confirmed'|'rejected';
export interface ReceiptImportSuggestion<T>{value:T;confidence:'low'|'medium'|'high';evidence:string}
export interface ReceiptImportDraft{ id:string;version:1;receiptId:string;fileName:string;status:ReceiptImportDraftStatus;suggestions:{merchant?:ReceiptImportSuggestion<string>;purchaseDate?:ReceiptImportSuggestion<string>;totalMinorUnits?:ReceiptImportSuggestion<number>;category?:ReceiptImportSuggestion<string>;description?:ReceiptImportSuggestion<string>};history:{id:string;at:string;by:string;event:'created'|'confirmed'|'rejected';note?:string}[];createdAt:string;updatedAt:string }
export const RECEIPT_IMPORT_DRAFT_STORAGE_KEY='liv.receipt-import-drafts.v1';export const RECEIPT_IMPORT_DRAFT_CHANGE_EVENT='liv:receipt-import-drafts-changed';
const read=(storage:Storage):ReceiptImportDraft[]=>{try{const value=JSON.parse(storage.getItem(RECEIPT_IMPORT_DRAFT_STORAGE_KEY)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
const assertDraft=(draft:ReceiptImportDraft)=>{if(!draft.id||!draft.receiptId||!draft.fileName)throw new Error('Importutkastet saknar obligatorisk identitet.');if(!['pending_review','confirmed','rejected'].includes(draft.status))throw new Error('Importutkastet har ogiltig status.');if(!draft.history.length)throw new Error('Importutkastet saknar historik.')};
export function createReceiptImportDraft(input:{receiptId:string;fileName:string;suggestions:ReceiptImportDraft['suggestions'];actor:string}):ReceiptImportDraft{const at=new Date().toISOString();const draft:ReceiptImportDraft={id:`receipt-import-${input.receiptId}`,version:1,receiptId:input.receiptId,fileName:input.fileName,status:'pending_review',suggestions:input.suggestions,history:[{id:`receipt-import-history-${Date.now()}-${Math.random().toString(16).slice(2)}`,at,by:input.actor,event:'created'}],createdAt:at,updatedAt:at};assertDraft(draft);return draft}
export function decideReceiptImportDraft(draft:ReceiptImportDraft,decision:'confirmed'|'rejected',actor:string,note?:string):ReceiptImportDraft{if(draft.status!=='pending_review')throw new Error('Importutkastet har redan behandlats.');const at=new Date().toISOString();const next={...draft,status:decision,history:[...draft.history,{id:`receipt-import-history-${Date.now()}-${Math.random().toString(16).slice(2)}`,at,by:actor,event:decision,note}],updatedAt:at};assertDraft(next);return next}
export function createLocalReceiptImportDraftRepository(storage:Storage=localStorage){return{list:()=>read(storage),get:(id:string)=>read(storage).find(item=>item.id===id),save:(draft:ReceiptImportDraft)=>{assertDraft(draft);const current=read(storage);storage.setItem(RECEIPT_IMPORT_DRAFT_STORAGE_KEY,JSON.stringify(current.some(item=>item.id===draft.id)?current.map(item=>item.id===draft.id?draft:item):[draft,...current]));if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(RECEIPT_IMPORT_DRAFT_CHANGE_EVENT,{detail:{draftId:draft.id}}))}}}
