import{createFinancialTransaction,fingerprintTransaction}from'./aggregate';import type{FinancialTransactionRecord,TransactionSourceFormat}from'./contracts';
export interface ParsedTransaction{bookedOn:string;valueOn?:string;minorUnits:number;direction:'debit'|'credit';counterparty?:string;description:string;bankReference?:string;rowKey:string}
const normaliseDate=(value:string)=>{const match=value.trim().match(/(\d{4})[-/.](\d{2})[-/.](\d{2})|(\d{2})[-/.](\d{2})[-/.](\d{4})/);if(!match)return'';return match[1]?`${match[1]}-${match[2]}-${match[3]}`:`${match[6]}-${match[5]}-${match[4]}`};
const parseAmount=(value:string)=>{const cleaned=value.replace(/\s/g,'').replace(/[^0-9,.-]/g,'').replace(/,(?=\d{1,2}$)/,'.');const number=Number(cleaned);return Number.isFinite(number)?Math.round(number*100):0};
function delimiterOf(line:string){return[';','\t',','].sort((a,b)=>line.split(b).length-line.split(a).length)[0]}
export function parseCsvTransactions(text:string):ParsedTransaction[]{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delimiter=delimiterOf(lines[0]);const rows=lines.map(line=>line.split(delimiter).map(cell=>cell.replace(/^"|"$/g,'').trim()));const headers=rows[0].map(h=>h.toLowerCase());const find=(terms:string[])=>headers.findIndex(header=>terms.some(term=>header.includes(term)));const findAll=(terms:string[])=>headers.map((header,index)=>terms.some(term=>header.includes(term))?index:-1).filter(index=>index>=0);const firstPopulated=(row:string[],indices:number[])=>indices.map(index=>row[index]?.trim()).find(Boolean)||'';const dateIndex=find(['bokföringsdag','bokföringsdatum','datum','date']);const valueIndex=find(['valutadag','value date']);const amountIndex=find(['belopp','amount']);const descriptionIndices=findAll(['rubrik','text','beskrivning','meddelande','description','namn']);const counterpartyIndices=findAll(['namn','mottagare','avsändare','motpart','counterparty']);const referenceIndex=find(['referens','ocr','reference']);if(dateIndex<0||amountIndex<0||descriptionIndices.length===0)throw new Error('CSV-filen måste innehålla datum, belopp och beskrivning.');return rows.slice(1).map<ParsedTransaction>((row,index)=>{const signed=parseAmount(row[amountIndex]||'');const description=firstPopulated(row,descriptionIndices);const counterparty=firstPopulated(row,counterpartyIndices)||undefined;return{bookedOn:normaliseDate(row[dateIndex]||''),valueOn:valueIndex>=0?normaliseDate(row[valueIndex]||'')||undefined:undefined,minorUnits:Math.abs(signed),direction:signed<0?'debit':'credit',counterparty,description,bankReference:referenceIndex>=0?row[referenceIndex]||undefined:undefined,rowKey:`csv-${index+2}`}}).filter(row=>Boolean(row.bookedOn&&row.minorUnits>0&&row.description))}
const firstText=(element:Element,names:string[])=>{for(const name of names){const nodes=element.getElementsByTagNameNS('*',name);if(nodes.length&&nodes[0].textContent?.trim())return nodes[0].textContent.trim()}return''};
export function parseCamt053Transactions(text:string):ParsedTransaction[]{const document=new DOMParser().parseFromString(text,'application/xml');if(document.querySelector('parsererror'))throw new Error('CAMT.053-filen är inte giltig XML.');const entries=[...document.getElementsByTagNameNS('*','Ntry')];return entries.map<ParsedTransaction>((entry,index)=>{const amountElement=entry.getElementsByTagNameNS('*','Amt')[0];const signed=parseAmount(amountElement?.textContent||'');const creditDebit=firstText(entry,['CdtDbtInd']);const bookedOn=normaliseDate(firstText(entry,['DtTm','Dt']));const description=firstText(entry,['Ustrd','AddtlNtryInf','RmtInf','EndToEndId'])||'Banktransaktion';return{bookedOn,minorUnits:Math.abs(signed),direction:creditDebit==='DBIT'?'debit':'credit',counterparty:firstText(entry,['Nm'])||undefined,description,bankReference:firstText(entry,['AcctSvcrRef','EndToEndId'])||undefined,rowKey:`camt-${index+1}`}}).filter(row=>Boolean(row.bookedOn&&row.minorUnits>0))}
export function parseStatement(format:TransactionSourceFormat,text:string){return format==='camt053'?parseCamt053Transactions(text):parseCsvTransactions(text)}
export function materialiseTransactions(rows:ParsedTransaction[],input:{accountId:string;fileName:string;format:TransactionSourceFormat;importId:string;importedBy:string;existingFingerprints:Set<string>}):{records:FinancialTransactionRecord[];duplicates:number}{const records:FinancialTransactionRecord[]=[];let duplicates=0;for(const row of rows){const fingerprint=fingerprintTransaction({accountId:input.accountId,bookedOn:row.bookedOn,minorUnits:row.minorUnits,direction:row.direction,description:row.description,bankReference:row.bankReference});if(input.existingFingerprints.has(fingerprint)){duplicates++;continue}const record=createFinancialTransaction({...row,accountId:input.accountId,fileName:input.fileName,format:input.format,importId:input.importId,importedBy:input.importedBy});records.push(record);input.existingFingerprints.add(record.fingerprint)}return{records,duplicates}}
