import React,{FormEvent,useEffect,useMemo,useState} from 'react';
import './action-system.css';

type ActionTab='inbox'|'steps'|'decisions'|'meetings'|'voice'|'myday';
type SourceType='Observation'|'Dokument'|'Resan'|'Kunskap'|'Ekonomi'|'Person'|'Idag'|'Möte'|'Familjen';
type NextStep={id:string;title:string;description:string;owner:string;due:string;status:'Öppen'|'Pågår'|'Klar';sourceType:SourceType;sourceLabel:string;createdAt:string};
type Decision={id:string;question:string;decision:string;reason:string;affects:string[];participants:string;date:string;reviewDate:string;status:'Aktivt'|'Klart'|'Ersatt'};
type Meeting={id:string;title:string;date:string;with:string;purpose:string;questions:string;documents:string;viktorWants:string;notes:string;decisions:string;nextActions:string;status:'Planerat'|'Genomfört'};
type VoiceEntry={id:string;kind:'Viktor sa'|'Viktor valde'|'Viktor vill'|'Viktor vill inte'|'Familjens tolkning';statement:string;context:string;date:string;author:string};
type DayItem={id:string;time:string;title:string;detail:string;kind:string;done:boolean};
type Profile={about:string;joys:string[];communication:string;stress:string;support:string};

const keys={steps:'liv.next-steps.v1',decisions:'liv.decisions.v1',meetings:'liv.meetings.v1',voice:'liv.viktor-voice.v1'};
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const humanDate=(value:string)=>value?new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)):'Inget datum';
function useStored<T>(key:string,fallback:T){const[state,setState]=useState<T>(()=>read(key,fallback));useEffect(()=>localStorage.setItem(key,JSON.stringify(state)),[key,state]);return[state,setState]as const}

const defaultSteps:NextStep[]=[{id:'step-1',title:'Boka två studiebesök',description:'Besök två dagliga verksamheter tillsammans med Viktor och dokumentera vad som känns tryggt respektive svårt.',owner:'Ben',due:'2026-08-15',status:'Öppen',sourceType:'Dokument',sourceLabel:'Beslut om daglig verksamhet',createdAt:new Date().toISOString()}];
const defaultDecisions:Decision[]=[{id:'decision-1',question:'Hur väljer vi daglig verksamhet?',decision:'Viktor ska besöka två verksamheter innan familjen väljer.',reason:'Beslutet ska bygga på Viktors upplevelse och inte bara på tillgänglighet.',affects:['Viktor','Familjen','Kommun'],participants:'Viktor, Ben och LSS-handläggare',date:today(),reviewDate:'2026-08-20',status:'Aktivt'}];

function Header(){return <><header className="action-header"><div><p>WORKSPACE · 09</p><h1>Handling</h1><span>Från förståelse till tydliga, ägda och spårbara nästa steg.</span></div><strong>Familjen beslutar</strong></header><section className="action-hero"><p>FÖRSTÅ · BESLUTA · AGERA</p><h2>Information ska hjälpa familjen framåt.</h2><span>Här samlas det som behöver uppmärksamhet, avgöras, genomföras eller uttryckas med Viktors egen röst.</span><i>→</i></section></>}

export function ActionSystem(){
 const[tab,setTab]=useState<ActionTab>('inbox');
 const[steps,setSteps]=useStored<NextStep[]>(keys.steps,defaultSteps);
 const[decisions,setDecisions]=useStored<Decision[]>(keys.decisions,defaultDecisions);
 const[meetings,setMeetings]=useStored<Meeting[]>(keys.meetings,[]);
 const[voices,setVoices]=useStored<VoiceEntry[]>(keys.voice,[]);
 const openSteps=steps.filter(x=>x.status!=='Klar');
 const upcomingMeetings=meetings.filter(x=>x.status==='Planerat');
 const attention=useMemo(()=>openSteps.length+upcomingMeetings.length+decisions.filter(x=>x.status==='Aktivt'&&x.reviewDate&&x.reviewDate<=today()).length,[openSteps,upcomingMeetings,decisions]);
 const tabs:[ActionTab,string,string][]=[['inbox','◎','Inkorg'],['steps','→','Nästa steg'],['decisions','◇','Beslut'],['meetings','▣','Möten'],['voice','♡','Viktors röst'],['myday','☀','Min dag']];
 return <main className="action-page"><Header/><nav className="action-tabs">{tabs.map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label}{id==='inbox'&&attention>0?<b>{attention}</b>:null}</button>)}</nav>
  {tab==='inbox'&&<Inbox steps={steps} decisions={decisions} meetings={meetings} setTab={setTab}/>} 
  {tab==='steps'&&<Steps items={steps} setItems={setSteps}/>} 
  {tab==='decisions'&&<Decisions items={decisions} setItems={setDecisions}/>} 
  {tab==='meetings'&&<Meetings items={meetings} setItems={setMeetings} addStep={x=>setSteps(current=>[x,...current])} addDecision={x=>setDecisions(current=>[x,...current])}/>} 
  {tab==='voice'&&<Voice items={voices} setItems={setVoices}/>} 
  {tab==='myday'&&<MyDay/>}
 </main>
}

function SectionTitle({n,kicker,title,copy}:{n:string;kicker:string;title:string;copy:string}){return <header className="action-section-title"><span>{n}</span><div><p>{kicker}</p><h2>{title}</h2><small>{copy}</small></div></header>}

function Inbox({steps,decisions,meetings,setTab}:{steps:NextStep[];decisions:Decision[];meetings:Meeting[];setTab:(x:ActionTab)=>void}){
 const open=steps.filter(x=>x.status!=='Klar');const planned=meetings.filter(x=>x.status==='Planerat');const reviews=decisions.filter(x=>x.status==='Aktivt'&&x.reviewDate&&x.reviewDate<=today());
 const total=open.length+planned.length+reviews.length;
 return <section className="action-surface"><SectionTitle n="01" kicker="FAMILJENS UPPMÄRKSAMHET" title={total?`${total} saker behöver familjen.`:'Allt är omhändertaget.'} copy="Inte notiser. Bara sådant som faktiskt behöver förstås, tilldelas eller avslutas."/>
  <div className="inbox-grid">
   <button onClick={()=>setTab('steps')}><i>→</i><span><small>ÖPPNA NÄSTA STEG</small><strong>{open.length}</strong><p>{open[0]?.title||'Inga öppna handlingar'}</p></span></button>
   <button onClick={()=>setTab('meetings')}><i>▣</i><span><small>PLANERADE MÖTEN</small><strong>{planned.length}</strong><p>{planned[0]?.title||'Inga planerade möten'}</p></span></button>
   <button onClick={()=>setTab('decisions')}><i>◇</i><span><small>BESLUT ATT FÖLJA UPP</small><strong>{reviews.length}</strong><p>{reviews[0]?.decision||'Inga beslut behöver omprövas'}</p></span></button>
  </div>
  <div className="attention-list">{open.slice(0,4).map(x=><article key={x.id}><span className="attention-dot"/><div><small>{x.sourceType} · {x.sourceLabel}</small><h3>{x.title}</h3><p>{x.owner||'Ingen ansvarig'} · {humanDate(x.due)}</p></div><b>{x.status}</b></article>)}{total===0&&<article className="calm-empty"><span>✓</span><div><h3>Familjen har kontroll.</h3><p>Nya saker visas här först när de faktiskt kräver uppmärksamhet.</p></div></article>}</div>
 </section>
}

function Steps({items,setItems}:{items:NextStep[];setItems:React.Dispatch<React.SetStateAction<NextStep[]>>}){
 const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),title=String(d.get('title')||'').trim();if(!title)return;setItems(current=>[{id:uid('step'),title,description:String(d.get('description')||''),owner:String(d.get('owner')||''),due:String(d.get('due')||''),status:'Öppen',sourceType:String(d.get('sourceType')||'Familjen') as SourceType,sourceLabel:String(d.get('sourceLabel')||'Skapad av familjen'),createdAt:new Date().toISOString()},...current]);f.reset()};
 return <section className="action-surface"><SectionTitle n="02" kicker="ÄGT ARBETE" title="Nästa steg" copy="Varje handling har ett ansvar, ett datum och ett tydligt ursprung."/><div className="action-cards">{items.map(x=><article key={x.id} className={x.status==='Klar'?'complete':''}><header><div><small>{x.sourceType} · {x.sourceLabel}</small><h3>{x.title}</h3></div><select value={x.status} onChange={e=>setItems(current=>current.map(i=>i.id===x.id?{...i,status:e.target.value as NextStep['status']}:i))}><option>Öppen</option><option>Pågår</option><option>Klar</option></select></header><p>{x.description}</p><footer><span><b>ANSVAR</b>{x.owner||'Ej tilldelad'}</span><span><b>DATUM</b>{humanDate(x.due)}</span><button onClick={()=>setItems(current=>current.filter(i=>i.id!==x.id))}>Ta bort</button></footer></article>)}</div><Editor title="Skapa nästa steg"><form onSubmit={add}><div className="action-form-grid"><label>Vad ska göras?<input name="title" required/></label><label>Ansvarig<input name="owner" placeholder="Ben, familjen…"/></label><label>Förfallodatum<input name="due" type="date"/></label><label>Skapat från<select name="sourceType">{['Familjen','Dokument','Observation','Resan','Kunskap','Ekonomi','Person','Idag','Möte'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Koppling<input name="sourceLabel" placeholder="Namn på dokument, möte eller fråga"/></label><label>Beskrivning<textarea name="description"/></label><button className="action-primary">+ Skapa nästa steg</button></form></Editor></section>
}

function Decisions({items,setItems}:{items:Decision[];setItems:React.Dispatch<React.SetStateAction<Decision[]>>}){
 const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),decision=String(d.get('decision')||'').trim();if(!decision)return;setItems(current=>[{id:uid('decision'),question:String(d.get('question')||''),decision,reason:String(d.get('reason')||''),affects:String(d.get('affects')||'').split(',').map(x=>x.trim()).filter(Boolean),participants:String(d.get('participants')||''),date:String(d.get('date')||today()),reviewDate:String(d.get('reviewDate')||''),status:'Aktivt'},...current]);f.reset()};
 return <section className="action-surface"><SectionTitle n="03" kicker="DET FAMILJEN HAR AVGJORT" title="Beslut" copy="Frågan, beslutet och varför det togs hålls ihop — med tid för omprövning."/><div className="decision-ledger">{items.map(x=><article key={x.id}><header><div><small>{humanDate(x.date)} · {x.participants}</small><h3>{x.question||'Familjens beslut'}</h3></div><select value={x.status} onChange={e=>setItems(current=>current.map(i=>i.id===x.id?{...i,status:e.target.value as Decision['status']}:i))}><option>Aktivt</option><option>Klart</option><option>Ersatt</option></select></header><blockquote>{x.decision}</blockquote><div className="decision-meta"><div><b>VARFÖR</b><p>{x.reason||'Ingen motivering sparad.'}</p></div><div><b>PÅVERKAR</b><p>{x.affects.join(' · ')||'Inte angivet'}</p></div><div><b>OMPRÖVAS</b><p>{humanDate(x.reviewDate)}</p></div></div><button className="remove" onClick={()=>setItems(current=>current.filter(i=>i.id!==x.id))}>Ta bort</button></article>)}</div><Editor title="Spara ett beslut"><form onSubmit={add}><div className="action-form-grid"><label>Frågan<input name="question"/></label><label>Datum<input name="date" type="date" defaultValue={today()}/></label><label>Deltagare<input name="participants"/></label><label>Följ upp<input name="reviewDate" type="date"/></label></div><label>Vad bestämdes?<textarea name="decision" required/></label><label>Varför?<textarea name="reason"/></label><label>Påverkar <small>separera med kommatecken</small><input name="affects" placeholder="Viktor, Familjen, Kommun"/></label><button className="action-primary">+ Spara beslut</button></form></Editor></section>
}

function Meetings({items,setItems,addStep,addDecision}:{items:Meeting[];setItems:React.Dispatch<React.SetStateAction<Meeting[]>>;addStep:(x:NextStep)=>void;addDecision:(x:Decision)=>void}){
 const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),title=String(d.get('title')||'').trim();if(!title)return;setItems(current=>[{id:uid('meeting'),title,date:String(d.get('date')||''),with:String(d.get('with')||''),purpose:String(d.get('purpose')||''),questions:String(d.get('questions')||''),documents:String(d.get('documents')||''),viktorWants:String(d.get('viktorWants')||''),notes:'',decisions:'',nextActions:'',status:'Planerat'},...current]);f.reset()};
 const update=(id:string,patch:Partial<Meeting>)=>setItems(current=>current.map(x=>x.id===id?{...x,...patch}:x));
 return <section className="action-surface"><SectionTitle n="04" kicker="FÖRE · UNDER · EFTER" title="Möten" copy="Rätt underlag före mötet. Beslut och nästa steg direkt efter."/><div className="meeting-list">{items.map(x=><article key={x.id}><header><div><small>{humanDate(x.date)} · {x.with}</small><h3>{x.title}</h3><p>{x.purpose}</p></div><select value={x.status} onChange={e=>update(x.id,{status:e.target.value as Meeting['status']})}><option>Planerat</option><option>Genomfört</option></select></header><div className="meeting-grid"><label>Frågor inför mötet<textarea value={x.questions} onChange={e=>update(x.id,{questions:e.target.value})}/></label><label>Dokument att ta med<textarea value={x.documents} onChange={e=>update(x.id,{documents:e.target.value})}/></label><label>Vad vill Viktor?<textarea value={x.viktorWants} onChange={e=>update(x.id,{viktorWants:e.target.value})}/></label><label>Anteckningar<textarea value={x.notes} onChange={e=>update(x.id,{notes:e.target.value})}/></label><label>Vad beslutades?<textarea value={x.decisions} onChange={e=>update(x.id,{decisions:e.target.value})}/></label><label>Vad händer nu?<textarea value={x.nextActions} onChange={e=>update(x.id,{nextActions:e.target.value})}/></label></div><footer><button disabled={!x.decisions.trim()} onClick={()=>addDecision({id:uid('decision'),question:x.purpose||x.title,decision:x.decisions,reason:`Beslutat under ${x.title}`,affects:['Viktor','Familjen'],participants:x.with,date:x.date||today(),reviewDate:'',status:'Aktivt'})}>◇ Skapa beslut</button><button disabled={!x.nextActions.trim()} onClick={()=>addStep({id:uid('step'),title:x.nextActions.split('\n')[0],description:x.nextActions,owner:'Familjen',due:'',status:'Öppen',sourceType:'Möte',sourceLabel:x.title,createdAt:new Date().toISOString()})}>→ Skapa nästa steg</button><button className="remove" onClick={()=>setItems(current=>current.filter(i=>i.id!==x.id))}>Ta bort</button></footer></article>)}</div><Editor title="Planera möte"><form onSubmit={add}><div className="action-form-grid"><label>Möte<input name="title" required/></label><label>Datum<input name="date" type="date"/></label><label>Med vilka?<input name="with"/></label><label>Syfte<input name="purpose"/></label></div><label>Frågor vi behöver få svar på<textarea name="questions"/></label><label>Dokument som ska med<textarea name="documents"/></label><label>Vad vill Viktor?<textarea name="viktorWants"/></label><button className="action-primary">+ Planera möte</button></form></Editor></section>
}

function Voice({items,setItems}:{items:VoiceEntry[];setItems:React.Dispatch<React.SetStateAction<VoiceEntry[]>>}){
 const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),statement=String(d.get('statement')||'').trim();if(!statement)return;setItems(current=>[{id:uid('voice'),kind:String(d.get('kind')||'Viktor sa') as VoiceEntry['kind'],statement,context:String(d.get('context')||''),date:String(d.get('date')||today()),author:String(d.get('author')||'Familjen')},...current]);f.reset()};
 return <section className="action-surface voice-surface"><SectionTitle n="05" kicker="VIKTORS EGEN RÖST" title="Det Viktor uttrycker." copy="Systemet skiljer alltid mellan Viktors ord, Viktors val och familjens tolkning."/><div className="voice-principle"><strong>Viktor har sagt</strong><span>är inte samma sak som</span><strong>familjen tror.</strong></div><div className="voice-list">{items.map(x=><article key={x.id} className={x.kind==='Familjens tolkning'?'interpretation':''}><small>{x.kind} · {humanDate(x.date)} · sparat av {x.author}</small><blockquote>“{x.statement}”</blockquote><p>{x.context}</p><button onClick={()=>setItems(current=>current.filter(i=>i.id!==x.id))}>Ta bort</button></article>)}{items.length===0&&<div className="voice-empty">Här finns ännu inget sparat med Viktors egen röst.</div>}</div><Editor title="Spara det Viktor uttryckt"><form onSubmit={add}><div className="action-form-grid"><label>Typ<select name="kind"><option>Viktor sa</option><option>Viktor valde</option><option>Viktor vill</option><option>Viktor vill inte</option><option>Familjens tolkning</option></select></label><label>Datum<input name="date" type="date" defaultValue={today()}/></label><label>Sparat av<input name="author" defaultValue="Familjen"/></label></div><label>Vad uttrycktes?<textarea name="statement" required/></label><label>Sammanhang<textarea name="context"/></label><button className="action-primary">+ Spara Viktors röst</button></form></Editor></section>
}

function MyDay(){const[items,setItems]=useState<DayItem[]>(()=>read('viktors-liv.today.v1',[]));const[profile]=useState<Profile>(()=>read('viktors-liv.person.v2',{about:'',joys:[],communication:'',stress:'',support:''}));useEffect(()=>{const refresh=()=>setItems(read('viktors-liv.today.v1',[]));window.addEventListener('storage',refresh);return()=>window.removeEventListener('storage',refresh)},[]);const visible=items.filter(x=>!x.done);return <section className="my-day"><header><p>VIKTOR IDAG</p><h2>God morgon Viktor <span>☀</span></h2><small>Det här händer idag. En sak i taget.</small></header><div className="my-day-grid"><section><h3>Idag händer detta</h3>{visible.map(x=><article key={x.id}><time>{x.time||'IDAG'}</time><div><strong>{x.title}</strong><p>{x.detail}</p></div></article>)}{visible.length===0&&<article><time>✓</time><div><strong>Ingen plan sparad ännu.</strong><p>Familjen kan lägga till dagens saker under Idag.</p></div></article>}</section><aside><h3>Kom ihåg</h3>{profile.joys.slice(0,6).map(x=><span key={x}>♥ {x}</span>)}<div className="my-day-calm"><b>När något ändras</b><p>{profile.support||'Berätta lugnt vad som händer härnäst.'}</p></div></aside></div></section>}

function Editor({title,children}:{title:string;children:React.ReactNode}){return <details className="action-editor"><summary><span>＋</span><strong>{title}</strong><i>Öppna</i></summary><div>{children}</div></details>}
