import React,{FormEvent,useEffect,useMemo,useState}from'react';
import{createFinancialActivity,createLocalFinancialActivityRepository,FINANCIAL_ACTIVITY_CHANGE_EVENT,markFinancialActivityReimbursed,projectFinancialActivitySummary,reviewFinancialActivity,type FinancialActivityRecord,type FinancialPayerKind,type PaymentMethod}from'./authorities/financial-activity';
import'./financial-activity-studio.css';

const categories=['Kläder','Hygien','Mat','Boende','Transport','Fritid','Vård','Hjälpmedel','Övrigt'];
const payerLabels:Record<FinancialPayerKind,string>={viktor:'Viktor',family:'Familjen',guardian:'God man',other:'Annan'};
const paymentLabels:Record<PaymentMethod,string>={card:'Kort',cash:'Kontant',bank_transfer:'Banköverföring',invoice:'Faktura',swish:'Swish',other:'Annat'};
const statusLabels:Record<FinancialActivityRecord['status'],string>={registered:'Registrerad',reviewed:'Kontrollerad',reported:'Redovisad',voided:'Makulerad'};
const money=(minorUnits:number)=>new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(minorUnits/100);
const today=()=>new Date().toISOString().slice(0,10);
function actor(){try{return JSON.parse(localStorage.getItem('liv.identity.session.v1')||'{}').identity?.name||'Familjen'}catch{return'Familjen'}}

export function FinancialActivityStudio(){
 const[items,setItems]=useState<FinancialActivityRecord[]>([]);const[open,setOpen]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const refresh=()=>setItems(createLocalFinancialActivityRepository().list());
 useEffect(()=>{refresh();const listener=()=>refresh();window.addEventListener(FINANCIAL_ACTIVITY_CHANGE_EVENT,listener);window.addEventListener('storage',listener);return()=>{window.removeEventListener(FINANCIAL_ACTIVITY_CHANGE_EVENT,listener);window.removeEventListener('storage',listener)}},[]);
 const active=useMemo(()=>items.filter(item=>item.status!=='voided'),[items]);const summary=useMemo(()=>projectFinancialActivitySummary(active),[active]);const pendingCount=active.filter(item=>item.reimbursement.status==='pending').length;
 const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');const form=event.currentTarget;const data=new FormData(form);try{const amount=Math.round(Number(data.get('amount')||0)*100);if(amount<=0)throw new Error('Beloppet måste vara större än 0 kronor.');const merchant=String(data.get('merchant')||'').trim();const description=String(data.get('description')||'').trim();if(!merchant||!description)throw new Error('Fyll i butik/mottagare och vad inköpet avsåg.');const receipt=String(data.get('receipt')||'').trim();const payerKind=String(data.get('payer')||'family')as FinancialPayerKind;const record=createFinancialActivity({occurredOn:String(data.get('date')||today()),merchant,description,payer:{kind:payerKind,name:payerKind==='other'?String(data.get('payerName')||'').trim()||undefined:undefined},paymentMethod:String(data.get('paymentMethod')||'card')as PaymentMethod,lines:[{description,category:String(data.get('category')||'Övrigt'),quantity:1,amount:{currency:'SEK',minorUnits:amount}}],evidence:receipt?[{id:`evidence-${Date.now()}`,kind:'receipt',fileRef:receipt,label:'Kvitto eller underlag'}]:[],reimbursementRequired:data.get('reimbursement')==='yes',createdBy:actor()});createLocalFinancialActivityRepository().save(record);form.reset();setOpen(false);setNotice(`Inköpet ”${record.description}” har registrerats.`)}catch(caught){setError(caught instanceof Error?caught.message:'Inköpet kunde inte sparas.')}};
 const review=(item:FinancialActivityRecord)=>{try{createLocalFinancialActivityRepository().save(reviewFinancialActivity(item,actor(),'Kontrollerad i Ekonomi'));setNotice('Inköpet är markerat som kontrollerat.')}catch(caught){setError(caught instanceof Error?caught.message:'Statusen kunde inte uppdateras.')}};
 const reimburse=(item:FinancialActivityRecord)=>{try{createLocalFinancialActivityRepository().save(markFinancialActivityReimbursed(item,today(),actor(),'Återbetalning registrerad i Ekonomi'));setNotice('Utlägget är markerat som återbetalt.')}catch(caught){setError(caught instanceof Error?caught.message:'Återbetalningen kunde inte registreras.')}};
 return <section className="financial-activity-studio" aria-labelledby="financial-activity-title"><div className="financial-activity-title"><span>02</span><div><p>FAKTISKA INKÖP · UTLÄGG · KVITTON</p><h2 id="financial-activity-title">Inköp och ekonomisk redovisning</h2><small>Registrera vad som faktiskt har köpts för Viktor och behåll underlag, betalare och återbetalningsstatus på samma ställe.</small></div><button onClick={()=>setOpen(value=>!value)}>+ Registrera inköp eller utlägg</button></div>
 <div className="financial-summary"><article><small>REGISTRERADE INKÖP</small><strong>{active.length}</strong><span>{money(summary.totalMinorUnits)}</span></article><article><small>VÄNTAR PÅ ÅTERBETALNING</small><strong>{pendingCount}</strong><span>{money(summary.pendingReimbursementMinorUnits)}</span></article><article><small>SAKNAR KVITTO</small><strong>{summary.missingEvidenceCount}</strong><span>behöver underlag</span></article></div>
 {notice&&<div className="financial-notice" role="status">✓ {notice}</div>}{error&&<div className="financial-error" role="alert">{error}</div>}
 {open&&<form className="financial-entry-form" onSubmit={save}><div className="financial-form-grid"><label>Datum<input name="date" type="date" defaultValue={today()} required/></label><label>Butik eller mottagare<input name="merchant" required placeholder="Till exempel H&M"/></label><label className="wide">Vad köptes eller betalades?<input name="description" required placeholder="Till exempel jacka och byxor till Viktor"/></label><label>Kategori<select name="category">{categories.map(category=><option key={category}>{category}</option>)}</select></label><label>Belopp i kronor<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Vem betalade?<select name="payer">{Object.entries(payerLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Betalningssätt<select name="paymentMethod">{Object.entries(paymentLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="wide">Kvitto eller filreferens<input name="receipt" placeholder="Filnamn, dokument-ID eller länk"/></label><label className="wide check"><input name="reimbursement" type="checkbox" value="yes"/><span>Detta är ett privat utlägg som ska återbetalas</span></label></div><footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Avbryt</button><button>Spara inköpet</button></footer></form>}
 <div className="financial-activity-list">{active.length?active.map(item=><article key={item.id}><div className="financial-date"><b>{new Date(`${item.occurredOn}T00:00:00`).toLocaleDateString('sv-SE',{day:'2-digit',month:'short'})}</b><small>{paymentLabels[item.paymentMethod]}</small></div><div><header><h3>{item.description}</h3><span className={`financial-status ${item.status}`}>{statusLabels[item.status]}</span></header><p>{item.merchant} · {payerLabels[item.payer.kind]} betalade</p><div className="financial-tags">{item.lines.map(line=><span key={line.id}>{line.category}</span>)}<span className={item.evidence.length?'has-evidence':'missing-evidence'}>{item.evidence.length?'Kvitto finns':'Kvitto saknas'}</span>{item.reimbursement.status==='pending'&&<span className="pending">Ej återbetald</span>}{item.reimbursement.status==='reimbursed'&&<span>Återbetald</span>}</div></div><strong className="financial-amount">{money(item.total.minorUnits)}</strong><div className="financial-actions">{item.status==='registered'&&<button onClick={()=>review(item)}>Markera kontrollerad</button>}{item.reimbursement.status==='pending'&&<button onClick={()=>reimburse(item)}>Markera återbetald</button>}</div></article>):<div className="financial-empty"><span>⌁</span><h3>Inga inköp registrerade ännu</h3><p>Nästa kvitto kan bli början på en samlad och enkel redovisning.</p><button onClick={()=>setOpen(true)}>+ Registrera första inköpet</button></div>}</div></section>
}
