import type{PopulationSeed}from'./authorities/resource-population';

export const SWEDISH_ORGANISATIONS_CATALOGUE:PopulationSeed[]=[
 {key:'attention-start',title:'Riksförbundet Attention – kunskap och stöd om NPF',type:'organisation',summary:'Nationell medlemsorganisation med kunskap, rådgivning och erfarenhetsbaserat stöd om neuropsykiatriska funktionsnedsättningar.',whyThisMatters:'Ger familjer och närstående en tydlig ingång till stöd, rättighetsfrågor och gemenskap kring NPF.',topics:['NPF','Anhörigstöd','Rättigheter'],keywords:['ADHD','autism','anhörig'],organisation:'Riksförbundet Attention',url:'https://attention.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'attention-anhorigfragor',title:'Frågor om NPF och anhörigskap',type:'family_guide',summary:'Attentions frågetjänst och samlade svar om vardagen som anhörig till en person med NPF.',whyThisMatters:'Ger igenkänning, praktiska perspektiv och en möjlighet att söka stöd i konkreta vardagsfrågor.',topics:['NPF','Anhörigstöd','Vardag'],keywords:['frågetjänst','närstående','rådgivning'],organisation:'Riksförbundet Attention',url:'https://attention.se/leva-med-npf/npf-stod/anhorigfragor/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'rbu-start',title:'RBU – Rörelsehindrade Barn och Ungdomar',type:'organisation',summary:'Riksförbund för barn och unga med rörelsenedsättning och deras familjer, med rådgivning, aktiviteter och påverkansarbete.',whyThisMatters:'Samlar juridiskt stöd, familjegemenskap och kunskap om barns rätt till stöd, skola, fritid och delaktighet.',topics:['Barn','Rörelsenedsättning','Anhörigstöd'],keywords:['RBU','familj','juridisk rådgivning'],organisation:'RBU',url:'https://rbu.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'rbu-funkisplats',title:'Funkisplats – tillgängliga aktiviteter',type:'website',summary:'Sökbar tjänst för tillgängliga aktiviteter och upplevelser för barn och unga med funktionsnedsättning.',whyThisMatters:'Gör det lättare att hitta en aktiv och social fritid där tillgänglighet redan har uppmärksammats.',topics:['Fritid','Tillgänglighet','Delaktighet'],keywords:['aktiviteter','karta','barn'],organisation:'RBU',url:'https://rbu.se/funkisplats/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'funktionsratt-sverige',title:'Funktionsrätt Sverige',type:'organisation',summary:'Paraplyorganisation som driver gemensamma funktionsrättsfrågor och bevakar jämlikhet, tillgänglighet och mänskliga rättigheter.',whyThisMatters:'Ger ett samlat perspektiv på strukturella hinder och aktuella rättighetsfrågor som berör många diagnosgrupper.',topics:['Funktionsrätt','Rättigheter','Delaktighet'],keywords:['jämlikhet','politik','tillgänglighet'],organisation:'Funktionsrätt Sverige',url:'https://funktionsratt.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'anhoriglinjen',title:'Anhöriglinjen',type:'website',summary:'Nationell stödlinje för anhöriga som behöver råd, vägledning eller någon att tala med.',whyThisMatters:'Ger ett lågtröskelstöd när anhörigrollen känns tung, ensam eller svår att orientera sig i.',topics:['Anhörigstöd','Hälsa','Samtalsstöd'],keywords:['stödlinje','närstående','rådgivning'],organisation:'Anhörigas Riksförbund',url:'https://anhorigasriksforbund.se/anhoriglinjen/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'nka-start',title:'Nationellt kompetenscentrum anhöriga',type:'organisation',summary:'Nationellt kunskapscentrum om anhörigfrågor, stödformer, forskning och utveckling.',whyThisMatters:'Samlar fördjupad och kvalitetssäkrad kunskap för både anhöriga och professionella som utformar stöd.',topics:['Anhörigstöd','Forskning','Kunskapsstöd'],keywords:['Nka','anhörig','kommun'],organisation:'Nationellt kompetenscentrum anhöriga',url:'https://anhoriga.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'habilitering-akk',title:'Kommunikation och AKK – introduktion',type:'government_guidance',summary:'Introduktion till alternativ och kompletterande kommunikation för närstående och personal.',whyThisMatters:'Ger konkreta strategier för att stödja kommunikation när tal inte räcker som enda uttryckssätt.',topics:['AKK','Kommunikation','Intellektuell funktionsnedsättning'],keywords:['bildstöd','tecken','kommunikationsstöd'],organisation:'Habilitering & Hälsa, Region Stockholm',url:'https://www.habilitering.se/kurskatalog/aktuella-kurser-i-datumordning/kommunikation-och-akk--en-introduktion-239/',trust:'official',catalogue:'Svenska organisationer och livsstöd'},
 {key:'dart-start',title:'Dart – kommunikations- och dataresurscenter',type:'organisation',summary:'Specialistverksamhet för kommunikation, AKK, tillgänglig information och kognitivt stöd.',whyThisMatters:'Ger familjer och professionella vägledning till metoder och hjälpmedel som stärker delaktighet och självbestämmande.',topics:['AKK','Hjälpmedel','Kommunikation'],keywords:['Dart','bildstöd','kognitivt stöd'],organisation:'Dart, Sahlgrenska universitetssjukhuset',url:'https://www.vgregion.se/ov/dart/',trust:'official',catalogue:'Svenska organisationer och livsstöd'},
 {key:'bildstod-start',title:'Bildstöd – skapa visuellt stöd',type:'website',summary:'Webbverktyg för att skapa bildstöd, scheman och tydliggörande material.',whyThisMatters:'Gör det möjligt att snabbt anpassa information och vardagsrutiner till personens kommunikativa behov.',topics:['Bildstöd','Kommunikation','Vardag'],keywords:['schema','symboler','tydliggörande'],organisation:'Dart',url:'https://bildstod.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'demenscentrum-if',title:'Demens vid intellektuell funktionsnedsättning',type:'government_guidance',summary:'Kunskap om demensutveckling, diagnostik och omsorg för personer med intellektuell funktionsnedsättning.',whyThisMatters:'Hjälper familjen och personal att skilja åldrande och demens från andra förändringar och söka rätt stöd i tid.',topics:['Åldrande','Demens','Intellektuell funktionsnedsättning'],keywords:['tidiga tecken','diagnostik','omsorg'],organisation:'Svenskt Demenscentrum',url:'https://demenscentrum.se/Arbeta-med-demens/vardkedjan/Utvecklingsstorning-demens/Om-demens-vid-utvecklingsstorning',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'demenscentrum-downs',title:'Downs syndrom och demens',type:'government_guidance',summary:'Fördjupning om tidig demensutveckling vid Downs syndrom och de krav det ställer på boende och omsorg.',whyThisMatters:'Gör det lättare att uppmärksamma förändrade behov och planera stöd som bevarar trygghet och kontinuitet.',topics:['Downs syndrom','Demens','Boende'],keywords:['Alzheimer','åldrande','gruppbostad'],organisation:'Svenskt Demenscentrum',url:'https://demenscentrum.se/arbeta-med-demens/vardkedjan/utvecklingsstorning-demens/downs-syndrom-och-demens',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'legimus-start',title:'Legimus – tillgängliga böcker',type:'website',summary:'Digitalt bibliotek med talböcker och andra tillgängliga medier för personer med läsnedsättning.',whyThisMatters:'Öppnar ett stort utbud av litteratur för personer som behöver lyssna eller läsa i anpassat format.',topics:['Läsning','Tillgänglighet','Fritid'],keywords:['talböcker','Legimus','läsnedsättning'],organisation:'Myndigheten för tillgängliga medier',url:'https://www.legimus.se/',trust:'official',catalogue:'Svenska organisationer och livsstöd'},
 {key:'parasport-start',title:'Parasport Sverige',type:'organisation',summary:'Nationell organisation för idrott och fysisk aktivitet för personer med funktionsnedsättning.',whyThisMatters:'Visar möjligheter till rörelse, tävling och gemenskap på olika nivåer och utifrån individuella förutsättningar.',topics:['Idrott','Fritid','Delaktighet'],keywords:['parasport','träning','förening'],organisation:'Svenska Parasportförbundet',url:'https://parasport.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'jag-start',title:'JAG – jämlik assistans och självbestämmande',type:'organisation',summary:'Brukarkooperativ och intresseorganisation för personer med stora funktionsnedsättningar och behov av personlig assistans.',whyThisMatters:'Ger erfarenhetsnära kunskap om självbestämmande, kommunikation och hur personlig assistans kan organiseras.',topics:['Personlig assistans','Självbestämmande','Rättigheter'],keywords:['JAG','brukarkooperativ','assistans'],organisation:'JAG',url:'https://jag.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'},
 {key:'ala-start',title:'Stiftelsen ALA – forskning och utveckling',type:'research',summary:'Forskning och kunskapsutveckling om intellektuell funktionsnedsättning och livsvillkor.',whyThisMatters:'Ger tillgång till svensk forskning som kan fördjupa förståelsen av stöd, delaktighet och vardagsliv.',topics:['Intellektuell funktionsnedsättning','Forskning','Livsvillkor'],keywords:['ALA','kunskapsutveckling','FUB'],organisation:'Stiftelsen ALA',url:'https://www.ala.fub.se/',trust:'professional',catalogue:'Svenska organisationer och livsstöd'}
];
