import type{PopulationSeed}from'./authorities/resource-population';

export const SWEDISH_VIDEOS_CATALOGUE:PopulationSeed[]=[
 {key:'video-spsm-if-emil',title:'Om intellektuell funktionsnedsättning – Det här är Emil',type:'video',summary:'En kort, undertextad film om vad intellektuell funktionsnedsättning kan innebära för lärande, delaktighet och behov av stöd.',whyThisMatters:'Ger familj och stödpersoner en konkret bild av hur miljö och bemötande kan öka tillgänglighet och delaktighet.',topics:['Intellektuell funktionsnedsättning','Lärande','Delaktighet'],keywords:['IF','tillgänglighet','undervisning'],audience:['Familj','Skola','Stödpersonal'],organisation:'Specialpedagogiska skolmyndigheten',url:'https://www.spsm.se/studiepaket-amnesomraden/moment-4/',trust:'official',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-spsm-autism-sinnesintryck',title:'Autism och sinnesintryck',type:'video',summary:'En person med egen erfarenhet beskriver hur ljud, ljus, dofter och andra sinnesintryck påverkar ork och koncentration.',whyThisMatters:'Hjälper omgivningen att förstå varför anpassningar av miljö, ljud och återhämtning kan vara avgörande.',topics:['Autism','Sinnesintryck','Tillgänglighet'],keywords:['sensorik','ljudmiljö','återhämtning'],audience:['Familj','Skola','Stödpersonal'],organisation:'Specialpedagogiska skolmyndigheten',url:'https://www.spsm.se/studiepaket-amnesomraden/moment-4/',trust:'official',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-spsm-akk-digitala-verktyg',title:'AKK, intellektuell funktionsnedsättning och digitala lärverktyg',type:'video',summary:'Filmer och studieunderlag om AKK, digitala verktyg och hur kommunikativt stöd kan stärka lärande och delaktighet.',whyThisMatters:'Ger praktiska exempel på hur kommunikation kan göras mer tillgänglig när talat språk inte räcker.',topics:['AKK','Kommunikation','Digitala hjälpmedel'],keywords:['bildstöd','kommunikationsstöd','lärverktyg'],audience:['Familj','Skola','Stödpersonal'],organisation:'Specialpedagogiska skolmyndigheten',url:'https://www.spsm.se/studiepaket-digitala-verktyg-och-akk/moment-1---om-akk-intellektuell-funktions--nedsattning-och-digitala-larverktyg-i-larandet/',trust:'official',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-autism-mik-appelgiljotinen',title:'Mik och äppelgiljotinen',type:'video',summary:'En tecknad kortfilm om autism, olikheter, sinneskänslighet, förändringar och styrkor.',whyThisMatters:'Kan användas som ett positivt och lättillgängligt underlag för samtal om autism i familjen eller skolan.',topics:['Autism','Barn','Förståelse'],keywords:['Mik','kortfilm','olikheter'],audience:['Barn','Familj','Skola'],organisation:'Autism Sverige',url:'https://www.autism.se/stod-och-rattigheter/stod-i-vardagen/for-dig-som-anhorig/mik-tecknad-kortfilm/',trust:'professional',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-socialstyrelsen-akk',title:'Webbutbildning – AKK som kommunikationsstöd',type:'video',summary:'Socialstyrelsens basutbildning med filmer och övningar om att använda alternativ och kompletterande kommunikation i verksamheter.',whyThisMatters:'Ger en gemensam kunskapsgrund för familj och personal kring hur AKK kan användas konsekvent i vardagen.',topics:['AKK','Kommunikation','Bemötande'],keywords:['webbutbildning','kommunikationsstöd','arbetsplats'],audience:['Stödpersonal','Familj','Verksamhet'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/webbutbildningar-inom-funktionshinderomradet/',trust:'official',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-socialstyrelsen-adhd-bemotande',title:'Att möta personer med adhd i socialtjänsten',type:'video',summary:'Fyra filmer om bemötande och om hur det kan vara att leva med adhd.',whyThisMatters:'Ger konkreta perspektiv som kan förbättra förståelse, kommunikation och bemötande i stödinsatser.',topics:['ADHD','Bemötande','Socialtjänst'],keywords:['NPF','filmer','diskussionsunderlag'],audience:['Stödpersonal','Familj','Socialtjänst'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/webbutbildningar-inom-funktionshinderomradet/',trust:'official',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-nka-daglig-verksamhet',title:'Meningsfull daglig verksamhet vid omfattande funktionsnedsättning',type:'video',summary:'Inspelat webbinarium om hur daglig verksamhet kan utformas för personer med omfattande funktionsnedsättningar.',whyThisMatters:'Ger familjer, gode män och verksamheter underlag för att bedöma innehåll, kvalitet och delaktighet i daglig verksamhet.',topics:['Daglig verksamhet','Delaktighet','Kvalitet'],keywords:['webbinarium','omfattande funktionsnedsättning','LSS'],audience:['Familj','God man','Verksamhet'],organisation:'Nationellt kompetenscentrum anhöriga',url:'https://anhoriga.se/stod--utbildning/webbinarier/webbinarier-2025/skapa-en-meningsfull-och-kvalitativ-daglig-verksamhet-for-personer-med-omfattande-funktionsnedsattning/',trust:'professional',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-nka-our-normal',title:'Our Normal – digitalt stöd för hela familjen',type:'video',summary:'Webbinarium om hur familjer med barn med funktionsnedsättning kan mötas, dela erfarenheter och få digitalt stöd.',whyThisMatters:'Visar hur gemenskap och erfarenhetsutbyte kan minska isolering och ge praktiskt stöd till hela familjen.',topics:['Anhörigstöd','Familj','Gemenskap'],keywords:['Our Normal','webbinarium','familjestöd'],audience:['Familj','Anhörig'],organisation:'Nationellt kompetenscentrum anhöriga',url:'https://anhoriga.se/anhorigomraden/flerfunktionsnedsattning/forsta-tiden/att-traffa-andra/webbinarium-om-our-normal/',trust:'professional',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-demens-tidiga-tecken',title:'Tidiga tecken – demens vid intellektuell funktionsnedsättning',type:'video',summary:'Webbutbildning med instruktionsfilmer om att upptäcka förändringar och tidiga tecken på demens hos personer med intellektuell funktionsnedsättning.',whyThisMatters:'Personer med intellektuell funktionsnedsättning kan behöva särskilt anpassad uppföljning när de åldras.',topics:['Demens','Åldrande','Intellektuell funktionsnedsättning'],keywords:['tidiga tecken','kartläggning','LSS'],audience:['Familj','God man','Stödpersonal'],organisation:'Svenskt Demenscentrum',url:'https://webhostdc.demenscentrum.se/arbeta-med-demens/teman/lss-intellektuell-funktionsnedsattning',trust:'professional',catalogue:'Svenska utbildningsfilmer'},
 {key:'video-socialstyrelsen-hygien-lss',title:'Basala hygienrutiner i LSS-boende',type:'video',summary:'Kostnadsfri webbutbildning med särskild modul för personal i LSS-boende och bostad med särskild service.',whyThisMatters:'Tydliga hygienrutiner skyddar både den enskilde och personalen och ger ett gemensamt arbetssätt i boendet.',topics:['LSS-boende','Hälsa','Hygien'],keywords:['smittskydd','omsorg','utbildning'],audience:['Stödpersonal','Verksamhet','Familj'],organisation:'Socialstyrelsen',url:'https://utbildning.socialstyrelsen.se/learn/courses/552/basala-hygienrutiner-i-vard-och-omsorg-2026',trust:'official',catalogue:'Svenska utbildningsfilmer'}
];
