import type{PopulationSeed}from'./authorities/resource-population';

export const SWEDISH_BOOKS_CATALOGUE:PopulationSeed[]=[
 {key:'book-gode-mannens-abc-2017',title:'Gode mannens abc',type:'book',summary:'Praktisk handbok för gode män och förvaltare med fokus på uppdragets juridik, ansvar och vardagliga genomförande.',whyThisMatters:'Ger ett samlat stöd för att förstå uppdraget och hantera återkommande frågor på ett strukturerat sätt.',topics:['God man','Förvaltarskap','Juridik'],keywords:['ställföreträdare','överförmyndare','redovisning'],organisation:'Wolters Kluwer',publisher:'Wolters Kluwer',author:'Jan Wallgren',publicationDate:'2017',isbn:'9789139115939',url:'https://libris.kb.se/bib/20698122',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-god-man-forvaltare-2016',title:'God man och förvaltare – en handbok',type:'book',summary:'Handbok om reglerna för godmanskap och förvaltarskap samt hur uppdraget utförs i praktiken.',whyThisMatters:'Hjälper gode män och anhöriga att skilja mellan olika former av ställföreträdarskap och förstå rättigheter och skyldigheter.',topics:['God man','Förvaltarskap','Rättigheter'],keywords:['föräldrabalken','huvudman','samtycke'],organisation:'Studentlitteratur',publisher:'Studentlitteratur',author:'Daniel Sjöstedt och Peter Sporrstedt',publicationDate:'2016',isbn:'9789144110257',url:'https://libris.kb.se/bib/19600647',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-god-man-eller-forvaltare-2007',title:'God man eller förvaltare – en praktisk handbok',type:'book',summary:'Praktisk introduktion till god man och förvaltare med exempel på ansvar, ekonomi och kontakten med myndigheter.',whyThisMatters:'Passar som grundbok när någon är ny i uppdraget eller behöver repetera gränserna för sitt ansvar.',topics:['God man','Ekonomi','Myndighetskontakter'],keywords:['praktisk handbok','huvudman','uppdrag'],organisation:'Natur & Kultur',publisher:'Natur & Kultur',author:'Kerstin Fälldin',publicationDate:'2007',isbn:'9789127357303',url:'https://libris.kb.se/bib/10172174',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-god-man-forvaltare-2007',title:'God man – förvaltare',type:'book',summary:'Översikt över godmanskap och förvaltarskap, rättsliga ramar och det praktiska uppdraget.',whyThisMatters:'Ger ytterligare ett etablerat referensverk för familjer och ställföreträdare som behöver jämföra vägledning.',topics:['God man','Förvaltarskap','Juridik'],keywords:['ställföreträdarskap','förmynderskap','ansvar'],organisation:'Studentlitteratur',publisher:'Studentlitteratur',author:'Ann-Charlotte Dahlstedt och Gunilla Björnefeldt-Rex',publicationDate:'2007',isbn:'9789144029719',url:'https://libris.kb.se/bib/10469427',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-downs-syndrom-1996',title:'Downs syndrom – en bok för föräldrar och personal',type:'book',summary:'Bred svensk introduktion till Downs syndrom med medicinska, pedagogiska, kommunikativa och sociala perspektiv.',whyThisMatters:'Samlar flera viktiga områden på ett ställe och kan ge både familj och personal en gemensam kunskapsgrund.',topics:['Downs syndrom','Hälsa','Kommunikation'],keywords:['trisomi 21','motorik','sociala rättigheter'],organisation:'Liber',publisher:'Liber utbildning',author:'Göran Annerén med flera',publicationDate:'1996',isbn:'9163415801',url:'https://libris.kb.se/bib/7456391',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-barn-med-downs-syndrom-1997',title:'Barn med Downs syndrom – i familjeperspektiv',type:'book',summary:'Bok som belyser barns utveckling och familjens situation ur ett svenskt familjeperspektiv.',whyThisMatters:'Ger erfarenhetsnära kunskap om hur Downs syndrom påverkar hela familjen och vilket stöd som kan behövas.',topics:['Downs syndrom','Familjeliv','Barn'],keywords:['familjeperspektiv','utveckling','stöd'],organisation:'Natur & Kultur',publisher:'Natur & Kultur',author:'Evy Kollberg (red.)',publicationDate:'1997',isbn:'9127064735',url:'https://libris.kb.se/bib/7229813',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-vagen-till-sjalvstandighet-2007',title:'Vägen till självständighet – Downs syndrom',type:'book',summary:'Kort bok om utveckling, självständighet och möjligheter för personer med Downs syndrom.',whyThisMatters:'Lyfter ett styrke- och framtidsperspektiv och kan inspirera till konkreta mål för ökad självständighet.',topics:['Downs syndrom','Självständighet','Vuxenliv'],keywords:['delaktighet','utveckling','framtid'],organisation:'Recito',publisher:'Recito',author:'Lisbeth ”Flisan” Andersson',publicationDate:'2007',isbn:'9789185879809',url:'https://libris.kb.se/bib/10686721',trust:'professional',catalogue:'Svenska böcker 1'},
 {key:'book-overbefalhavarens-hemlighet-2016',title:'Överbefälhavarens hemlighet',type:'book',summary:'Svensk roman där Downs syndrom är en central del av berättelsen och samhällsbilden.',whyThisMatters:'Skönlitteratur kan skapa samtal om bemötande, människovärde, fördomar och hur samhället ser på funktionsnedsättning.',topics:['Downs syndrom','Skönlitteratur','Bemötande'],keywords:['roman','samhälle','människovärde'],organisation:'Bonnier',publisher:'Bonnier',author:'Björn Ranelid',publicationDate:'2016',isbn:'9789100156411',url:'https://libris.kb.se/bib/18546355',trust:'professional',catalogue:'Svenska böcker 1'}
];
