import type{PopulationSeed}from'./authorities/resource-population';

export const SWEDISH_STARTER_CATALOGUE:PopulationSeed[]=[
 {key:'1177-downs-syndrom',title:'Downs syndrom – 1177',type:'government_guidance',summary:'Medicinskt granskad introduktion till Downs syndrom, hälsa, utveckling och kommunikation.',whyThisMatters:'Ger familjen en trygg översikt över vanliga hälsobehov och hur stöd kan underlätta ett långt och gott liv.',topics:['Downs syndrom','Hälsa','Kommunikation'],keywords:['trisomi 21','habilitering','tecken som stöd'],organisation:'1177 Vårdguiden',url:'https://www.1177.se/sjukdomar--besvar/hjarna-och-nerver/larande-forstaelse-och-minne/downs-syndrom/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'1177-intellektuell-funktionsnedsattning',title:'Intellektuell funktionsnedsättning – 1177',type:'government_guidance',summary:'Översikt över intellektuell funktionsnedsättning, utredning, stöd och vardagsstrategier.',whyThisMatters:'Hjälper familjen att förstå behov, styrkor och stöd som kan göra vardagen mer självständig och förutsägbar.',topics:['Intellektuell funktionsnedsättning','Hälsa','Vardag'],keywords:['IF','utvecklingsstörning','rutiner'],organisation:'1177 Vårdguiden',url:'https://www.1177.se/Skane/sjukdomar--besvar/hjarna-och-nerver/larande-forstaelse-och-minne/intellektuell-funktionsnedsattning---utvecklingsstorning/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'fk-vuxen-funktionsnedsattning',title:'Stöd för vuxna med funktionsnedsättning',type:'government_guidance',summary:'Försäkringskassans samlade ingång till aktivitetsersättning, sjukersättning, merkostnadsersättning, assistans och bilstöd.',whyThisMatters:'Gör det enklare att hitta rätt statlig ersättning och förstå vilket stöd som kan vara aktuellt.',topics:['Ekonomi','Försäkringskassan','Funktionsnedsättning'],keywords:['ersättning','bidrag','ansökan'],organisation:'Försäkringskassan',url:'https://www.forsakringskassan.se/privatperson/vuxen-med-funktionsnedsattning',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'fk-assistans-vuxna',title:'Assistansersättning för vuxna',type:'government_guidance',summary:'Villkor, belopp och ansökningsväg för statlig assistansersättning till vuxna.',whyThisMatters:'Ger en tydlig startpunkt när hjälpbehoven är omfattande och personlig assistans kan vara aktuell.',topics:['Personlig assistans','LSS','Ekonomi'],keywords:['grundläggande behov','20 timmar','ansökan'],organisation:'Försäkringskassan',url:'https://www.forsakringskassan.se/privatperson/vuxen-med-funktionsnedsattning/assistansersattning/assistansersattning-for-vuxna',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'fk-barn-extra-stod',title:'Barn med funktionsnedsättning eller behov av extra stöd',type:'government_guidance',summary:'Samlad information om omvårdnadsbidrag, merkostnadsersättning, kontaktdagar, assistans och bilstöd.',whyThisMatters:'Hjälper familjer att se vilka ekonomiska stöd som kan finnas kring ett barns behov.',topics:['Barn','Ekonomi','Försäkringskassan'],keywords:['omvårdnadsbidrag','merkostnad','kontaktdagar'],organisation:'Försäkringskassan',url:'https://www.forsakringskassan.se/privatperson/familj-och-barn/barn-med-funktionsnedsattning-eller-behov-av-extra-stod',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'fk-ersattningar-a-o',title:'Försäkringskassans ersättningar A–Ö',type:'government_guidance',summary:'Alfabetisk översikt över Försäkringskassans ersättningar och stöd.',whyThisMatters:'Bra som uppslagsverk när familjen vet vad stödet heter men behöver hitta rätt information eller ansökan.',topics:['Ekonomi','Myndigheter'],keywords:['ersättningar','blanketter','ansökan'],organisation:'Försäkringskassan',url:'https://www.forsakringskassan.se/privatperson/ersattningar-a-o',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'socialstyrelsen-funktionshinder',title:'Stöd inom funktionshindersområdet',type:'government_guidance',summary:'Socialstyrelsens samlade kunskapsstöd om LSS, daglig verksamhet, hjälpmedel, boende och delaktighet.',whyThisMatters:'Ger tillgång till nationella kunskapsstöd och vägledningar för både familjer och professionella.',topics:['LSS','Funktionshinder','Delaktighet'],keywords:['kunskapsstöd','socialtjänst','jämlikhet'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'socialstyrelsen-regelverk',title:'Regelverk inom funktionshindersområdet',type:'legislation',summary:'Samlad vägledning till lagar, föreskrifter, allmänna råd och handböcker inom funktionshinder och LSS.',whyThisMatters:'Hjälper familjen och gode mannen att hitta rätt rättsligt underlag och förstå vilka regler som styr stödet.',topics:['LSS','Juridik','Rättigheter'],keywords:['lagar','föreskrifter','rättssäkerhet'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/regelverk/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'socialstyrelsen-daglig-verksamhet',title:'Daglig verksamhet enligt LSS',type:'government_guidance',summary:'Kunskapsstöd om syfte, kvalitet, deltagande, habiliteringsersättning och regler för daglig verksamhet.',whyThisMatters:'Ger familjen bättre underlag för samtal om innehåll, kvalitet och Viktors utveckling i daglig verksamhet.',topics:['Daglig verksamhet','LSS','Arbete'],keywords:['habiliteringsersättning','sysselsättning','delaktighet'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/daglig-verksamhet-lss/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'socialstyrelsen-hjalpmedel',title:'Hjälpmedel för personer med funktionsnedsättning',type:'government_guidance',summary:'Nationell information om hjälpmedel för aktivitet, delaktighet, självständighet och behandling.',whyThisMatters:'Hjälper familjen att förstå vad hjälpmedel kan bidra med och vilka frågor som är viktiga vid förskrivning.',topics:['Hjälpmedel','Självständighet','Hälsa'],keywords:['förskrivning','vardagshjälpmedel','rehabilitering'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/hjalpmedel/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'socialstyrelsen-stod-utbildning',title:'Kunskapsstöd och utbildning inom funktionshinder',type:'government_guidance',summary:'Vägledningar och utbildningsmaterial om bemötande, kompetens, anhöriga och stöd till personer med funktionsnedsättning.',whyThisMatters:'Ger praktiska verktyg för bättre bemötande och mer personcentrerat stöd.',topics:['Bemötande','Utbildning','Anhörigstöd'],keywords:['kompetens','personal','jämlika villkor'],organisation:'Socialstyrelsen',url:'https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/funktionshinder/stod-och-utbildning/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'riksdagen-lss',title:'Lag (1993:387) om stöd och service till vissa funktionshindrade',type:'legislation',summary:'Den fullständiga och aktuella lagtexten för LSS.',whyThisMatters:'LSS är en central rättighetslag och den primära källan när familjen behöver kontrollera vad lagen faktiskt säger.',topics:['LSS','Juridik','Rättigheter'],keywords:['lagtext','insatser','personkrets'],organisation:'Sveriges riksdag',url:'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/lag-1993387-om-stod-och-service-till_sfs-1993-387/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'riksdagen-foraldrabalken',title:'Föräldrabalk (1949:381)',type:'legislation',summary:'Aktuell lagtext om bland annat god man, förvaltare och ställföreträdarskap.',whyThisMatters:'Är den juridiska grundkällan för gode mannens uppdrag, ansvar och befogenheter.',topics:['God man','Juridik','Förvaltarskap'],keywords:['föräldrabalken','ställföreträdare','överförmyndare'],organisation:'Sveriges riksdag',url:'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/foraldrabalk-1949381_sfs-1949-381/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'ivo-lss',title:'IVO – stöd och service enligt LSS',type:'government_guidance',summary:'Information om tillsyn, tillstånd, klagomål och rättigheter inom LSS-verksamheter.',whyThisMatters:'Visar vart familjen kan vända sig när det finns allvarliga brister eller frågor om en verksamhets ansvar.',topics:['LSS','Tillsyn','Klagomål'],keywords:['IVO','lex Sarah','tillstånd'],organisation:'Inspektionen för vård och omsorg',url:'https://www.ivo.se/privatpersoner/omsorg-och-lss/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'spsm-intellektuell-funktionsnedsattning',title:'SPSM – intellektuell funktionsnedsättning',type:'government_guidance',summary:'Pedagogisk information om lärande, tillgänglighet och stöd för personer med intellektuell funktionsnedsättning.',whyThisMatters:'Ger konkreta perspektiv på hur information, undervisning och miljö kan anpassas.',topics:['Lärande','Intellektuell funktionsnedsättning','Tillgänglighet'],keywords:['specialpedagogik','anpassning','skola'],organisation:'Specialpedagogiska skolmyndigheten',url:'https://www.spsm.se/funktionsnedsattningar/intellektuell-funktionsnedsattning/',trust:'official',catalogue:'Svensk grundvåg 1'},
 {key:'fub-kunskap',title:'FUB – kunskap och stöd',type:'organisation',summary:'Riksförbundet FUB:s information, rådgivning och material för personer med intellektuell funktionsnedsättning och deras närstående.',whyThisMatters:'Kombinerar erfarenhetsbaserad kunskap, rättighetsfrågor och stöd från en etablerad brukarorganisation.',topics:['Intellektuell funktionsnedsättning','Rättigheter','Anhörigstöd'],keywords:['FUB','rådgivning','förening'],organisation:'Riksförbundet FUB',url:'https://www.fub.se/',trust:'professional',catalogue:'Svensk grundvåg 1'},
 {key:'downforeningen',title:'Svenska Downföreningen',type:'organisation',summary:'Kunskap, nätverk och stöd för personer med Downs syndrom, familjer och professionella.',whyThisMatters:'Ger tillgång till erfarenheter, aktuella frågor och gemenskap specifikt kring Downs syndrom.',topics:['Downs syndrom','Anhörigstöd','Gemenskap'],keywords:['Downföreningen','trisomi 21','familj'],organisation:'Svenska Downföreningen',url:'https://www.svenskadownforeningen.se/',trust:'professional',catalogue:'Svensk grundvåg 1'},
 {key:'autism-sverige',title:'Autism Sverige',type:'organisation',summary:'Kunskap, rådgivning och intressepolitiskt arbete för personer med autism och deras närstående.',whyThisMatters:'Ger fördjupad diagnoskunskap och praktiskt stöd från en nationell medlemsorganisation.',topics:['Autism','Anhörigstöd','Rättigheter'],keywords:['autismspektrum','rådgivning','förening'],organisation:'Autism Sverige',url:'https://www.autism.se/',trust:'professional',catalogue:'Svensk grundvåg 1'},
 {key:'anhorigas-riksforbund',title:'Anhörigas Riksförbund',type:'organisation',summary:'Stöd, kunskap och opinionsarbete för personer som hjälper eller vårdar en närstående.',whyThisMatters:'Påminner om att även anhöriga behöver stöd, återhämtning och kunskap för att orka över tid.',topics:['Anhörigstöd','Hälsa','Rättigheter'],keywords:['anhörig','avlösning','stödlinje'],organisation:'Anhörigas Riksförbund',url:'https://anhorigasriksforbund.se/',trust:'professional',catalogue:'Svensk grundvåg 1'},
 {key:'mfd-delaktighet',title:'Myndigheten för delaktighet',type:'government_guidance',summary:'Nationell kunskap om tillgänglighet, delaktighet och levnadsvillkor för personer med funktionsnedsättning.',whyThisMatters:'Ger ett bredare rättighets- och samhällsperspektiv på hinder, tillgänglighet och självbestämmande.',topics:['Delaktighet','Tillgänglighet','Rättigheter'],keywords:['MFD','funktionshinderspolitik','universell utformning'],organisation:'Myndigheten för delaktighet',url:'https://www.mfd.se/',trust:'official',catalogue:'Svensk grundvåg 1'}
];
