import React,{FormEvent,useEffect,useMemo,useState}from'react';
import{archiveKnowledgeTopic,createKnowledgeTopic,createLocalKnowledgeTopicRepository,restoreKnowledgeTopic,updateKnowledgeTopic,type KnowledgeTopicRecord,type KnowledgeTopicStatus}from'./authorities/knowledge';
import'./knowledge-studio.css';

const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);
const repo=()=>createLocalKnowledgeTopicRepository();

type Filter='all'|KnowledgeTopicStatus;

export function KnowledgeStudio(){
 const[topics,setTopics]=useState<KnowledgeTopicRecord[]>(()=>repo().list());const[selectedId,setSelectedId]=useState('');const[query,setQuery]=useState('');const[filter,setFilter]=useState<Filter>('active');const[editing,setEditing]=useState(false);const[creating,setCreating]=useState(false);const[notice,setNotice]=useState('');
 const refresh=()=>setTopics(repo().list());
 useEffect(()=>{const listener=()=>refresh();window.addEventListener('liv:knowledge-changed',listener);window.addEventListener('storage',listener);return()=>{window.removeEventListener('liv:knowledge-changed',listener);window.removeEventListener('storage',listener)}},[]);
 const visible=useMemo(()=>topics.filter(topic=>{const hay=[topic.title,topic.description,topic.category,...topic.aliases].join(' ').toLowerCase();return(filter==='all'||topic.status===filter)&&(!query.trim()||hay.includes(query.trim().toLowerCase()))}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),[topics,query,filter]);
 const selected=topics.find(topic=>topic.id===selectedId)||visible[0]||null;
 useEffect(()=>{if(selected&&!selectedId)setSelectedId(selected.id)},[selected,selectedId]);
 const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),title=String(data.get('title')||'').trim(),description=String(data.get('description')||'').trim(),category=String(data.get('category')||'').trim(),aliases=split(String(data.get('aliases')||''));if(!title||!description){setNotice('Titel och beskrivning måste fyllas i.');return}const actor=String(data.get('actor')||'Familjen').trim()||'Familjen';const next=creating?createKnowledgeTopic({title,description,category,aliases,createdBy:actor}):updateKnowledgeTopic(selected!,{title,description,category,aliases},actor,'Redigerad i Knowledge Studio');repo().save(next);setSelectedId(next.id);setCreating(false);setEditing(false);setNotice(`Kunskapsämnet ”${next.title}” har sparats.`)};
 const changeStatus=()=>{if(!selected)return;const actor='Familjen';const next=selected.status==='active'?archiveKnowledgeTopic(selected,actor,'Arkiverad i Knowledge Studio'):restoreKnowledgeTopic(selected,actor,'Återställd i Knowledge Studio');repo().save(next);setNotice(next.status==='archived'?'Kunskapsämnet har arkiverats.':'Kunskapsämnet har återställts.')};
 const startCreate=()=>{setCreating(true);setEditing(true);setNotice('')};
 const activeCount=topics.filter(topic=>topic.status==='active').length,archivedCount=topics.length-activeCount;
 return <main className="knowledge-studio">
  <header className="ks-head"><div><p>STUDIO · KNOWLEDGE</p><h1>Kunskapsämnen</h1><span>Det familjen uttryckligen vill förstå — samlat, sökbart och förvaltat över tid.</span></div><button className="ks-primary" onClick={startCreate}>＋ Nytt kunskapsämne</button></header>
  {notice&&<div className="ks-notice" role="status">{notice}</div>}
  <section className="ks-stats"><article><strong>{activeCount}</strong><span>aktiva ämnen</span></article><article><strong>{archivedCount}</strong><span>arkiverade</span></article><article><strong>{topics.reduce((sum,topic)=>sum+topic.aliases.length,0)}</strong><span>alias och sökord</span></article></section>
  <section className="ks-toolbar"><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Sök titel, kategori, beskrivning eller alias"/></label><select value={filter} onChange={event=>setFilter(event.target.value as Filter)}><option value="active">Aktiva</option><option value="archived">Arkiverade</option><option value="all">Alla</option></select></section>
  <section className="ks-layout"><aside className="ks-list"><header><b>{visible.length} ämnen</b><small>liv.knowledge-authority.v1</small></header>{visible.map(topic=><button key={topic.id} className={selected?.id===topic.id&&!creating?'active':''} onClick={()=>{setSelectedId(topic.id);setCreating(false);setEditing(false);setNotice('')}}><span>◇</span><div><strong>{topic.title}</strong><small>{topic.category||'Ingen kategori'} · {topic.status==='active'?'Aktiv':'Arkiverad'}</small></div></button>)}{visible.length===0&&<div className="ks-empty">Inga kunskapsämnen matchar filtret.</div>}</aside>
   <section className="ks-detail">{editing?<TopicEditor topic={creating?null:selected} onSave={save} onCancel={()=>{setEditing(false);setCreating(false)}}/>:selected?<><header className="ks-topic-head"><div><small>{selected.category||'KUNSKAPSÄMNE'}</small><h2>{selected.title}</h2><p>{selected.status==='active'?'Aktivt ämne':'Arkiverat ämne'}</p></div><div><button onClick={()=>setEditing(true)}>Redigera</button><button onClick={changeStatus}>{selected.status==='active'?'Arkivera':'Återställ'}</button></div></header><article className="ks-description"><b>DET HÄR BEHÖVER FAMILJEN FÖRSTÅ</b><p>{selected.description}</p></article><section className="ks-meta"><article><b>ALIAS OCH SÖKORD</b>{selected.aliases.length?<div>{selected.aliases.map(alias=><span key={alias}>{alias}</span>)}</div>:<p>Inga alias sparade.</p>}</article><article><b>HISTORIK</b><ol>{[...selected.history].reverse().slice(0,6).map(entry=><li key={entry.id}><span>{entry.event}</span><small>{new Intl.DateTimeFormat('sv-SE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(entry.at))} · {entry.by}</small></li>)}</ol></article></section><footer className="ks-authority-note">Kunskapsämnet stödjer förståelse. Det äger aldrig sanningen om Viktor eller någon annan person.</footer></>:<div className="ks-placeholder"><span>◇</span><h2>Skapa det första kunskapsämnet</h2><p>Beskriv ett område som familjen uttryckligen vill förstå bättre.</p><button className="ks-primary" onClick={startCreate}>Nytt kunskapsämne</button></div>}</section>
  </section>
 </main>
}

function TopicEditor({topic,onSave,onCancel}:{topic:KnowledgeTopicRecord|null;onSave:(event:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}){return <form className="ks-editor" onSubmit={onSave}><header><div><p>KNOWLEDGE AUTHORITY</p><h2>{topic?'Redigera kunskapsämne':'Nytt kunskapsämne'}</h2></div><button type="button" onClick={onCancel}>Stäng</button></header><label>Titel *<input name="title" defaultValue={topic?.title} required autoFocus/></label><label>Vad behöver familjen förstå? *<textarea name="description" rows={6} defaultValue={topic?.description} required/></label><div className="ks-form-grid"><label>Kategori<input name="category" defaultValue={topic?.category}/></label><label>Författad av<input name="actor" defaultValue="Familjen"/></label></div><label>Alias och sökord — separera med kommatecken<input name="aliases" defaultValue={topic?.aliases.join(', ')}/></label><footer><button type="button" onClick={onCancel}>Avbryt</button><button className="ks-primary">Spara kunskapsämne</button></footer></form>}
