import React,{useEffect,useMemo,useState}from'react';
import{createLocalResourcePackRepository,createLocalResourceRepository,projectResourceCard,projectResourcePack,searchResources,type ResourceRecord,type ResourceType}from'./authorities/resource';
import'./resource-studio.css';

const labels:Record<ResourceType,string>={book:'Böcker',website:'Webbplatser',pdf:'Dokument',legislation:'Lagstiftning',government_guidance:'Myndigheter',organisation:'Organisationer',video:'Video',podcast:'Podcasts',research:'Forskning',checklist:'Checklistor',template:'Mallar',family_guide:'Guider',personal_note:'Egna anteckningar',external_link:'Externa länkar'};
const icons:Record<ResourceType,string>={book:'▤',website:'◎',pdf:'▱',legislation:'§',government_guidance:'⌂',organisation:'◉',video:'▶',podcast:'◌',research:'⌁',checklist:'✓',template:'□',family_guide:'♡',personal_note:'✎',external_link:'↗'};
const featured:ResourceType[]=['book','website','pdf','government_guidance','video','podcast','family_guide'];
type Filter='all'|ResourceType|'packs';

export function ResourceStudio(){
 const[resources,setResources]=useState<ResourceRecord[]>([]);const[packs,setPacks]=useState(()=>createLocalResourcePackRepository().list());const[query,setQuery]=useState('');const[filter,setFilter]=useState<Filter>('all');const[showAdd,setShowAdd]=useState(false);
 const refresh=()=>{setResources(createLocalResourceRepository().list());setPacks(createLocalResourcePackRepository().list())};
 useEffect(()=>{refresh();const listener=()=>refresh();window.addEventListener('storage',listener);window.addEventListener('liv:resources-changed',listener);return()=>{window.removeEventListener('storage',listener);window.removeEventListener('liv:resources-changed',listener)}},[]);
 const visible=useMemo(()=>{const found=query.trim()?searchResources(resources,{text:query,limit:100}).map(result=>result.resource):resources;return filter==='all'||filter==='packs'?found:found.filter(resource=>resource.type===filter)},[resources,query,filter]);
 const cards=visible.map(projectResourceCard);const packCards=packs.map(projectResourcePack);
 const openAdd=()=>setShowAdd(true);const openPacks=()=>setFilter('packs');
 return <main className="resource-studio u-page">
  <header className="resource-head"><div><p>STUDIO · 08</p><h1>Resurser</h1><span>Betrodd information som hjälper familjen att förstå.</span></div><button className="resource-primary" onClick={openAdd}>+ Lägg till resurs</button></header>
  <div className="resource-page-grid"><div className="resource-main">
   <section className="resource-statement"><div><p>FÖRSTÅELSE · KÄLLOR · TILLIT</p><h2>Hitta rätt hjälp när den behövs.</h2><span>Böcker, webbplatser, vägledning och familjens erfarenhet samlas på ett ställe — alltid med en tydlig förklaring till varför resursen spelar roll.</span></div><div className="resource-hero-art" aria-hidden="true"><span>♧</span><b>▥</b></div></section>
   <nav className="resource-categories" aria-label="Resurskategorier"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><span>▤</span>Alla resurser</button>{featured.map(type=><button className={filter===type?'active':''} onClick={()=>setFilter(type)} key={type}><span>{icons[type]}</span>{labels[type]}</button>)}<button className={filter==='packs'?'active':''} onClick={openPacks}><span>▣</span>Paket</button></nav>
   <div className="resource-toolbar"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Sök resurser..."/></label><select aria-label="Typ" value={filter==='packs'?'packs':filter} onChange={event=>setFilter(event.target.value as Filter)}><option value="all">Alla typer</option>{(Object.keys(labels)as ResourceType[]).map(type=><option value={type} key={type}>{labels[type]}</option>)}<option value="packs">Paket</option></select><select aria-label="Sortering"><option>Senast tillagda</option><option>Titel A–Ö</option></select><div className="resource-view-toggle"><button className="active" aria-label="Kortvy">▦</button><button aria-label="Listvy">☷</button></div></div>
   <section className="resource-results">{filter==='packs'?<>{packCards.length?<div className="pack-grid">{packCards.map(pack=><article key={pack.id}><small>{pack.status}</small><h3>{pack.name}</h3><p>{pack.description}</p><footer><span>{pack.resourceCount} resurser</span><b>{pack.publisher}</b></footer></article>)}</div>:<Empty title="Inga resurspaket ännu" copy="Skapa eller installera en betrodd samling för exempelvis God man, LSS eller autism." action="Skapa första paketet" secondary="Lägg till resurs" onAction={openAdd} onSecondary={openAdd}/>}</>:cards.length?<div className="resource-card-list">{cards.map(card=><article key={card.id}><div className="resource-icon">{icons[resources.find(item=>item.id===card.id)?.type||'external_link']}</div><div className="resource-card-body"><header><div><small>{labels[resources.find(item=>item.id===card.id)?.type||'external_link']}</small><h3>{card.title}</h3></div><strong>{card.trust.replace('_',' ')}</strong></header><p>{card.summary}</p><blockquote><b>VARFÖR DETTA SPELAR ROLL</b>{card.whyThisMatters}</blockquote><footer>{card.topics.map(topic=><span key={topic}>{topic}</span>)}{card.locator&&<a href={card.locator.startsWith('http')?card.locator:undefined} target="_blank" rel="noreferrer">Öppna ↗</a>}</footer></div></article>)}</div>:<Empty title={query?'Ingen resurs matchar sökningen':'Inga resurser ännu'} copy={query?'Prova ett bredare ämne eller en annan formulering.':'Börja bygga familjens kunskapsbibliotek. Lägg till en resurs eller installera ett paket för att komma igång.'} action="+ Lägg till resurs" secondary="Utforska paket" onAction={openAdd} onSecondary={openPacks}/>}</section>
  </div><aside className="resource-aside"><section><p>SNABBSTATISTIK</p><div><span>▤</span><b>{resources.length}</b><small>resurser</small></div><div><span>▤</span><b>{packs.length}</b><small>paket</small></div></section><section><p>TIPS</p><div className="resource-tip"><span>♧</span><small>Använd ämnen och kategorier för att göra resurser enkla att hitta när ni behöver dem.</small></div></section></aside></div>
  {showAdd&&<div className="resource-dialog-backdrop" onMouseDown={()=>setShowAdd(false)}><section className="resource-dialog" onMouseDown={event=>event.stopPropagation()}><button className="resource-dialog-close" onClick={()=>setShowAdd(false)}>×</button><p>NÄSTA STEG · RA-2B</p><h2>Vad vill du lägga till?</h2><span>Resource Studio är anslutet till den riktiga Authority-lagringen. Nästa slice öppnar den guidade registreringen här.</span><div className="resource-choice-grid">{(['book','website','pdf','government_guidance','family_guide','personal_note']as ResourceType[]).map(type=><button key={type}><b>{icons[type]}</b><span>{labels[type]}</span></button>)}</div><button className="resource-primary" onClick={()=>setShowAdd(false)}>Stäng</button></section></div>}
 </main>
}

function Empty({title,copy,action,secondary,onAction,onSecondary}:{title:string;copy:string;action:string;secondary:string;onAction:()=>void;onSecondary:()=>void}){return <div className="resource-empty"><span>▤</span><h3>{title}</h3><p>{copy}</p><button className="resource-primary" onClick={onAction}>{action}</button><button className="resource-secondary" onClick={onSecondary}>{secondary}</button></div>}
