import React,{useEffect,useMemo,useState}from'react';
import{createLocalResourcePackRepository,createLocalResourceRepository,projectResourceCard,projectResourcePack,searchResources,type ResourceRecord,type ResourceType}from'./authorities/resource';
import'./resource-studio.css';

const labels:Record<ResourceType,string>={book:'Böcker',website:'Webbplatser',pdf:'PDF',legislation:'Lagstiftning',government_guidance:'Myndighetsvägledning',organisation:'Organisationer',video:'Video',podcast:'Poddar',research:'Forskning',checklist:'Checklistor',template:'Mallar',family_guide:'Familjeguider',personal_note:'Egna anteckningar',external_link:'Externa länkar'};
const icons:Record<ResourceType,string>={book:'▤',website:'◎',pdf:'▱',legislation:'§',government_guidance:'⌂',organisation:'◉',video:'▶',podcast:'◌',research:'⌁',checklist:'✓',template:'□',family_guide:'♡',personal_note:'✎',external_link:'↗'};
type Filter='all'|ResourceType|'packs';

export function ResourceStudio(){
 const[resources,setResources]=useState<ResourceRecord[]>([]);const[packs,setPacks]=useState(()=>createLocalResourcePackRepository().list());const[query,setQuery]=useState('');const[filter,setFilter]=useState<Filter>('all');const[showAdd,setShowAdd]=useState(false);
 const refresh=()=>{setResources(createLocalResourceRepository().list());setPacks(createLocalResourcePackRepository().list())};
 useEffect(()=>{refresh();const listener=()=>refresh();window.addEventListener('storage',listener);window.addEventListener('liv:resources-changed',listener);return()=>{window.removeEventListener('storage',listener);window.removeEventListener('liv:resources-changed',listener)}},[]);
 const visible=useMemo(()=>{const found=query.trim()?searchResources(resources,{text:query,limit:100}).map(result=>result.resource):resources;return filter==='all'||filter==='packs'?found:found.filter(resource=>resource.type===filter)},[resources,query,filter]);
 const cards=visible.map(projectResourceCard);const packCards=packs.map(projectResourcePack);
 const categoryCounts=resources.reduce<Partial<Record<ResourceType,number>>>((sum,resource)=>({...sum,[resource.type]:(sum[resource.type]||0)+1}),{});
 return <main className="resource-studio u-page">
  <header className="resource-head"><div><p>STUDIO · 08</p><h1>Resurser</h1><span>Betrodd information som hjälper familjen att förstå.</span></div><button className="resource-primary" onClick={()=>setShowAdd(true)}>+ Lägg till resurs</button></header>
  <section className="resource-statement"><div><p>FÖRSTÅELSE · KÄLLOR · TILLIT</p><h2>Hitta rätt hjälp när den behövs.</h2><span>Böcker, webbplatser, vägledning och familjens erfarenhet samlas på ett ställe — alltid med en tydlig förklaring till varför resursen spelar roll.</span></div><aside><b>{resources.length}</b><span>resurser</span><b>{packs.length}</b><span>paket</span></aside></section>
  <div className="resource-toolbar"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Sök efter ämne, titel eller varför det spelar roll"/></label><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Alla</button><button className={filter==='packs'?'active':''} onClick={()=>setFilter('packs')}>Resurspaket</button></div>
  <div className="resource-layout"><nav className="resource-categories"><p>KATEGORIER</p><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><span>◇</span><b>Alla resurser</b><small>{resources.length}</small></button>{(Object.keys(labels)as ResourceType[]).map(type=><button className={filter===type?'active':''} onClick={()=>setFilter(type)} key={type}><span>{icons[type]}</span><b>{labels[type]}</b><small>{categoryCounts[type]||0}</small></button>)}</nav>
   <section className="resource-results">{filter==='packs'?<><div className="resource-section-title"><div><p>RESURSPAKET</p><h2>Färdiga samlingar för ett område</h2></div><button onClick={()=>setShowAdd(true)}>+ Skapa paket</button></div>{packCards.length?<div className="pack-grid">{packCards.map(pack=><article key={pack.id}><small>{pack.status}</small><h3>{pack.name}</h3><p>{pack.description}</p><footer><span>{pack.resourceCount} resurser</span><b>{pack.publisher}</b></footer></article>)}</div>:<Empty title="Inga resurspaket ännu" copy="Skapa en betrodd samling för exempelvis God man, LSS eller autism." action="Skapa första paketet" onAction={()=>setShowAdd(true)}/>}</>:<><div className="resource-section-title"><div><p>{filter==='all'?'ALLA RESURSER':labels[filter as ResourceType].toUpperCase()}</p><h2>{query?`Resultat för “${query}”`:'Familjens betrodda bibliotek'}</h2></div><span>{cards.length} träffar</span></div>{cards.length?<div className="resource-card-list">{cards.map(card=><article key={card.id}><div className="resource-icon">{icons[resources.find(item=>item.id===card.id)?.type||'external_link']}</div><div className="resource-card-body"><header><div><small>{labels[resources.find(item=>item.id===card.id)?.type||'external_link']}</small><h3>{card.title}</h3></div><strong>{card.trust.replace('_',' ')}</strong></header><p>{card.summary}</p><blockquote><b>VARFÖR DETTA SPELAR ROLL</b>{card.whyThisMatters}</blockquote><footer>{card.topics.map(topic=><span key={topic}>{topic}</span>)}{card.locator&&<a href={card.locator.startsWith('http')?card.locator:undefined} target="_blank" rel="noreferrer">Öppna ↗</a>}</footer></div></article>)}</div>:<Empty title={query?'Ingen resurs matchar sökningen':'Biblioteket väntar på sin första resurs'} copy={query?'Prova ett bredare ämne eller en annan formulering.':'Börja med en bok, webbplats eller egen anteckning som gjort något lättare att förstå.'} action="Lägg till resurs" onAction={()=>setShowAdd(true)}/>}</>}</section>
  </div>
  {showAdd&&<div className="resource-dialog-backdrop" onMouseDown={()=>setShowAdd(false)}><section className="resource-dialog" onMouseDown={event=>event.stopPropagation()}><button className="resource-dialog-close" onClick={()=>setShowAdd(false)}>×</button><p>NÄSTA STEG · RA-2B</p><h2>Vad vill du lägga till?</h2><span>Resource Studio är nu anslutet till den riktiga Authority-lagringen. Nästa slice öppnar den guidade registreringen här.</span><div className="resource-choice-grid">{(['book','website','pdf','government_guidance','family_guide','personal_note']as ResourceType[]).map(type=><button key={type}><b>{icons[type]}</b><span>{labels[type]}</span></button>)}</div><button className="resource-primary" onClick={()=>setShowAdd(false)}>Stäng</button></section></div>}
 </main>
}

function Empty({title,copy,action,onAction}:{title:string;copy:string;action:string;onAction:()=>void}){return <div className="resource-empty"><span>◇</span><h3>{title}</h3><p>{copy}</p><button onClick={onAction}>{action}</button></div>}
