import React,{useEffect,useMemo,useRef,useState}from'react';
import{assertResource,connectResource,createLocalResourceRepository,createResource,reviewResource,updateResource,type ResourceConnections,type ResourceRecord,type ResourceTrust,type ResourceType}from'./authorities/resource';
import{connectionGroups,readResourceConnectionRegistry,type ConnectionKind}from'./resource-connection-registry';
import'./resource-wizard.css';

const types:[ResourceType,string,string][]= [['book','▤','Bok'],['website','◎','Webbplats'],['pdf','▱','PDF'],['government_guidance','⌂','Myndighetsvägledning'],['family_guide','♡','Familjeguide'],['personal_note','✎','Egen anteckning']];
const trustOptions:[ResourceTrust,string][]= [['unreviewed','Ej granskad'],['family_trusted','Betrodd av familjen'],['professional','Professionellt rekommenderad'],['official','Officiell källa']];
const emptyConnections:ResourceConnections={personIds:[],documentIds:[],lifeEventIds:[],knowledgeTopicIds:[],decisionIds:[]};
const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);
type Draft={type?:ResourceType;title:string;summary:string;whyThisMatters:string;author:string;organisation:string;publisher:string;edition:string;isbn:string;chapter:string;section:string;page:string;language:string;url:string;fileRef:string;publicationDate:string;note:string;topics:string;keywords:string;audience:string;trust:ResourceTrust;reviewedBy:string;reviewNote:string;connections:ResourceConnections};
const initial:Draft={title:'',summary:'',whyThisMatters:'',author:'',organisation:'',publisher:'',edition:'',isbn:'',chapter:'',section:'',page:'',language:'',url:'',fileRef:'',publicationDate:'',note:'',topics:'',keywords:'',audience:'',trust:'unreviewed',reviewedBy:'',reviewNote:'',connections:emptyConnections};
export function ResourceWizard({onClose,onSaved}:{onClose:()=>void;onSaved:(resource:ResourceRecord)=>void}){
 const[step,setStep]=useState(0);const[draft,setDraft]=useState<Draft>(initial);const[error,setError]=useState('');const dialogRef=useRef<HTMLElement>(null);const registry=useMemo(readResourceConnectionRegistry,[]);const dirty=useMemo(()=>JSON.stringify(draft)!==JSON.stringify(initial),[draft]);
 const requestClose=()=>{if(!dirty||window.confirm('Du har osparade ändringar. Vill du stänga utan att spara?'))onClose()};
 useEffect(()=>{dialogRef.current?.querySelector<HTMLElement>('button,input,textarea,select')?.focus();},[step]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();requestClose()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 const set=(patch:Partial<Draft>)=>{setDraft(current=>({...current,...patch}));setError('')};
 const toggle=(kind:ConnectionKind,id:string)=>set({connections:{...draft.connections,[kind]:draft.connections[kind].includes(id)?draft.connections[kind].filter(value=>value!==id):[...draft.connections[kind],id]}});
 const validate=()=>{if(step===0&&!draft.type)return'Välj vad du vill lägga till.';if(step===1&&(!draft.title.trim()||!draft.summary.trim()))return'Fyll i titel och en kort sammanfattning.';if(step===2&&!draft.whyThisMatters.trim())return'Förklara varför resursen spelar roll.';if(step===5&&!draft.reviewedBy.trim())return'Ange vem som har gjort granskningen.';return''};
 const next=()=>{const message=validate();if(message){setError(message);return}setStep(value=>Math.min(6,value+1))};
 const save=()=>{try{const actor=draft.reviewedBy.trim()||'Familjen';let record=createResource({title:draft.title,type:draft.type!,summary:draft.summary,whyThisMatters:draft.whyThisMatters,createdBy:actor});record=updateResource(record,{topics:split(draft.topics),keywords:split(draft.keywords),audience:split(draft.audience),source:{author:draft.author.trim()||undefined,organisation:draft.organisation.trim()||undefined,publisher:draft.publisher.trim()||undefined,edition:draft.edition.trim()||undefined,publicationDate:draft.publicationDate.trim()||undefined,language:draft.language.trim()||undefined},locator:{url:draft.url.trim()||undefined,isbn:draft.isbn.trim()||undefined,fileRef:draft.fileRef.trim()||undefined,chapter:draft.chapter.trim()||undefined,section:draft.section.trim()||undefined,page:draft.page.trim()||undefined}},actor,'Skapad i Resource Studio');record=connectResource(record,draft.connections,actor);record=reviewResource(record,{trust:draft.trust,reviewedBy:actor,note:draft.reviewNote.trim()||undefined});assertResource(record);createLocalResourceRepository().save(record);window.dispatchEvent(new CustomEvent('liv:resources-changed',{detail:{resourceId:record.id}}));onSaved(record)}catch(caught){setError(caught instanceof Error?caught.message:'Resursen kunde inte sparas.')}};
 const source=[draft.organisation,draft.author,draft.publisher].filter(Boolean).join(' · ');const connected=connectionGroups.flatMap(group=>registry[group.kind].filter(item=>draft.connections[group.kind].includes(item.id)).map(item=>item.label));
 return <div className="resource-dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&dirty)setError('Använd Avbryt för att hantera osparade ändringar.')}}><section className="resource-dialog resource-wizard" role="dialog" aria-modal="true" aria-labelledby="resource-wizard-title" ref={dialogRef}><button className="resource-dialog-close" aria-label="Stäng" onClick={requestClose}>×</button><p>STEG {step+1} AV 7</p><div className="resource-wizard-progress" aria-label={`Steg ${step+1} av 7`}>{Array.from({length:7},(_,index)=><span key={index} className={index<=step?'active':''}/>)}</div>
 {step===0&&<><h2 id="resource-wizard-title">Vad vill du lägga till?</h2><span>Välj den typ som bäst beskriver resursen.</span><div className="resource-choice-grid">{types.map(([type,icon,label])=><button className={draft.type===type?'selected':''} key={type} onClick={()=>{set({type});setStep(1)}}><b>{icon}</b><span>{label}</span></button>)}</div></>}
 {step===1&&<Identity draft={draft} set={set}/>} 
 {step===2&&<><h2 id="resource-wizard-title">Varför spelar detta roll?</h2><span>Förklara med egna ord hur resursen kan hjälpa familjen att förstå, välja eller agera.</span><label className="resource-field"><span>Varför detta spelar roll *</span><textarea rows={7} value={draft.whyThisMatters} onChange={e=>set({whyThisMatters:e.target.value})}/></label></>}
 {step===3&&<><h2 id="resource-wizard-title">Ämnen och målgrupp</h2><span>Skriv fria värden separerade med kommatecken.</span><label className="resource-field"><span>Ämnen</span><input value={draft.topics} onChange={e=>set({topics:e.target.value})} placeholder="LSS, Autism, Hälsa"/></label><label className="resource-field"><span>Nyckelord</span><input value={draft.keywords} onChange={e=>set({keywords:e.target.value})}/></label><label className="resource-field"><span>Målgrupp</span><input value={draft.audience} onChange={e=>set({audience:e.target.value})} placeholder="Familj, Professionella"/></label></>}
 {step===4&&<><h2 id="resource-wizard-title">Kopplingar</h2><span>Koppla resursen till verkliga poster som redan finns i LIV.</span><div className="resource-connection-groups">{connectionGroups.map(group=><section key={group.kind}><h3>{group.label}</h3>{registry[group.kind].length?<div className="resource-connection-list">{registry[group.kind].map(item=><label key={item.id}><input type="checkbox" checked={draft.connections[group.kind].includes(item.id)} onChange={()=>toggle(group.kind,item.id)}/><span><b>{item.label}</b>{item.meta&&<small>{item.meta}</small>}</span></label>)}</div>:<p className="resource-connection-empty">{group.empty}</p>}</section>)}</div></>}
 {step===5&&<><h2 id="resource-wizard-title">Tillit och granskning</h2><span>Tillitsnivån väljs alltid uttryckligen och antas aldrig automatiskt.</span><div className="resource-trust-grid">{trustOptions.map(([value,label])=><label key={value}><input type="radio" name="trust" checked={draft.trust===value} onChange={()=>set({trust:value})}/><span>{label}</span></label>)}</div><label className="resource-field"><span>Granskad av *</span><input value={draft.reviewedBy} onChange={e=>set({reviewedBy:e.target.value})}/></label><label className="resource-field"><span>Anteckning om granskningen</span><textarea rows={3} value={draft.reviewNote} onChange={e=>set({reviewNote:e.target.value})}/></label></>}
 {step===6&&<><h2 id="resource-wizard-title">Granska och spara</h2><span>Kontrollera att resursen beskriver hur den hjälper familjen att förstå.</span><dl className="resource-review"><div><dt>Typ</dt><dd>{types.find(item=>item[0]===draft.type)?.[2]}</dd></div><div><dt>Titel</dt><dd>{draft.title}</dd></div><div><dt>Källa</dt><dd>{source||'Inte angiven'}</dd></div><div><dt>Sammanfattning</dt><dd>{draft.summary}</dd></div><div><dt>Varför detta spelar roll</dt><dd>{draft.whyThisMatters}</dd></div><div><dt>Ämnen</dt><dd>{split(draft.topics).join(', ')||'Inga'}</dd></div><div><dt>Kopplingar</dt><dd>{connected.join(', ')||'Inga'}</dd></div><div><dt>Tillitsnivå</dt><dd>{trustOptions.find(item=>item[0]===draft.trust)?.[1]}</dd></div><div><dt>Var resursen finns</dt><dd>{draft.url||draft.fileRef||draft.isbn||'Inte angivet'}</dd></div></dl></>}
 {error&&<div className="resource-wizard-error" role="alert">{error}</div>}<footer className="resource-wizard-actions"><button className="resource-secondary" onClick={requestClose}>Avbryt</button>{step>0&&<button className="resource-secondary" onClick={()=>setStep(value=>value-1)}>Föregående</button>}<span/>{step<6&&step>0&&<button className="resource-primary" onClick={next}>Fortsätt</button>}{step===6&&<button className="resource-primary" onClick={save}>Spara resurs</button>}</footer></section></div>
}
function Identity({draft,set}:{draft:Draft;set:(patch:Partial<Draft>)=>void}){const type=draft.type!;return <><h2 id="resource-wizard-title">Identitet och källa</h2><span>Beskriv resursen kort och ange bara den källinformation ni känner till.</span><div className="resource-form-grid"><label className="resource-field full"><span>Titel *</span><input value={draft.title} onChange={e=>set({title:e.target.value})}/></label><label className="resource-field full"><span>Kort sammanfattning *</span><textarea rows={3} value={draft.summary} onChange={e=>set({summary:e.target.value})}/></label>{type==='personal_note'?<label className="resource-field full"><span>Själva anteckningen</span><textarea rows={5} value={draft.note} onChange={e=>set({note:e.target.value,summary:e.target.value})}/></label>:null}{['book','website','pdf','family_guide','personal_note'].includes(type)&&<label className="resource-field"><span>{type==='family_guide'||type==='personal_note'?'Författad av':'Författare'}</span><input value={draft.author} onChange={e=>set({author:e.target.value})}/></label>}{['website','pdf','government_guidance'].includes(type)&&<label className="resource-field"><span>Organisation eller myndighet</span><input value={draft.organisation} onChange={e=>set({organisation:e.target.value})}/></label>}{type==='book'&&<><label className="resource-field"><span>Utgivare</span><input value={draft.publisher} onChange={e=>set({publisher:e.target.value})}/></label><label className="resource-field"><span>Upplaga</span><input value={draft.edition} onChange={e=>set({edition:e.target.value})}/></label><label className="resource-field"><span>ISBN</span><input value={draft.isbn} onChange={e=>set({isbn:e.target.value})}/></label><label className="resource-field"><span>Kapitel</span><input value={draft.chapter} onChange={e=>set({chapter:e.target.value})}/></label></>}{type!=='personal_note'&&<><label className="resource-field"><span>URL</span><input value={draft.url} onChange={e=>set({url:e.target.value})}/></label><label className="resource-field"><span>Filreferens</span><input value={draft.fileRef} onChange={e=>set({fileRef:e.target.value})}/></label></>}<label className="resource-field"><span>Avsnitt</span><input value={draft.section} onChange={e=>set({section:e.target.value})}/></label><label className="resource-field"><span>Sida</span><input value={draft.page} onChange={e=>set({page:e.target.value})}/></label>{['book','website','pdf'].includes(type)&&<label className="resource-field"><span>Språk</span><input value={draft.language} onChange={e=>set({language:e.target.value})}/></label>}{type==='government_guidance'&&<label className="resource-field"><span>Datum eller version</span><input value={draft.publicationDate} onChange={e=>set({publicationDate:e.target.value})}/></label>}</div></>}
