import type{ReceiptRecord,ReceiptSource}from'./contracts';
import{assertReceipt}from'./invariants';

const now=()=>new Date().toISOString();
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const unique=(values:string[])=>[...new Set(values.map(value=>value.trim()).filter(Boolean))];
export function checksumReceiptSource(source:ReceiptSource):string{let hash=2166136261;const value=[source.kind,source.reference,source.originalName||'',source.mimeType||'',String(source.sizeBytes||'')].join('|');for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0')}
export interface CreateReceiptInput{source:ReceiptSource;capturedBy:string;capturedAt?:string;merchant?:string;purchaseDate?:string;totalMinorUnits?:number;pages?:number;documentIds?:string[]}
export function createReceipt(input:CreateReceiptInput):ReceiptRecord{const at=now();const record:ReceiptRecord={id:id('receipt'),version:1,status:'captured',source:{...input.source,reference:input.source.reference.trim()},checksum:{algorithm:'fnv1a32',value:checksumReceiptSource(input.source)},capturedAt:input.capturedAt||at,merchant:input.merchant?.trim()||undefined,purchaseDate:input.purchaseDate,totalMinorUnits:input.totalMinorUnits,currency:'SEK',pages:input.pages||1,ocr:{status:'not_requested'},review:{status:'unreviewed'},financialActivityIds:[],documentIds:unique(input.documentIds||[]),history:[{id:id('receipt-history'),at,by:input.capturedBy,event:'created'}],createdAt:at,updatedAt:at};assertReceipt(record);return record}
export function updateReceiptMetadata(record:ReceiptRecord,patch:Partial<Pick<ReceiptRecord,'merchant'|'purchaseDate'|'totalMinorUnits'|'pages'|'documentIds'>>,actor:string,note?:string):ReceiptRecord{if(record.status==='voided')throw new Error('Voided receipts cannot be changed.');const at=now();const next={...record,...patch,merchant:patch.merchant?.trim()||record.merchant,documentIds:patch.documentIds?unique(patch.documentIds):record.documentIds,history:[...record.history,{id:id('receipt-history'),at,by:actor,event:'metadata_updated' as const,note}],updatedAt:at};assertReceipt(next);return next}
export function linkReceiptToFinancialActivity(record:ReceiptRecord,activityId:string,actor:string):ReceiptRecord{if(record.status==='voided')throw new Error('Voided receipts cannot be linked.');const at=now();const next={...record,status:'linked' as const,financialActivityIds:unique([...record.financialActivityIds,activityId]),history:[...record.history,{id:id('receipt-history'),at,by:actor,event:'linked' as const,note:activityId}],updatedAt:at};assertReceipt(next);return next}
export function reviewReceipt(record:ReceiptRecord,actor:string,note?:string):ReceiptRecord{if(record.status==='voided')throw new Error('Voided receipts cannot be reviewed.');const at=now();const next={...record,review:{status:'reviewed' as const,reviewedBy:actor,reviewedAt:at,note},history:[...record.history,{id:id('receipt-history'),at,by:actor,event:'reviewed' as const,note}],updatedAt:at};assertReceipt(next);return next}
export function updateReceiptOcr(record:ReceiptRecord,status:ReceiptRecord['ocr']['status'],actor:string,payload?:{text?:string;error?:string}):ReceiptRecord{if(record.status==='voided')throw new Error('Voided receipts cannot receive OCR updates.');const at=now();const next={...record,ocr:{status,text:payload?.text,error:payload?.error},history:[...record.history,{id:id('receipt-history'),at,by:actor,event:'ocr_updated' as const,note:status}],updatedAt:at};assertReceipt(next);return next}
export function voidReceipt(record:ReceiptRecord,actor:string,note:string):ReceiptRecord{if(record.financialActivityIds.length>0)throw new Error('Linked receipts cannot be voided before their financial links are resolved.');const at=now();const next={...record,status:'voided' as const,history:[...record.history,{id:id('receipt-history'),at,by:actor,event:'voided' as const,note}],updatedAt:at};assertReceipt(next);return next}
